export const SEQUENCE_TYPE_TIMELAPSE = 'timelapse';

export const EXAMPLE_SKETCH_DATA_OBJECT = {
  "objects": [
    {
      "name": "Rectangle_test",
      "shape": "Rectangle",
      "properties": [
        { "property": "x", "value": 0 },
        { "property": "xMod", "value": 0 },
        { "property": "xModType", "value": "none" },
        { "property": "xIter", "value": 0 },
        { "property": "xIterFunc", "value": "none" },
        { "property": "xr", "value": 0 },
        { "property": "xrMod", "value": 0 },
        { "property": "xrModType", "value": "none" },
        { "property": "xrIter", "value": 0 },
        { "property": "xrIterFunc", "value": "none" },
        { "property": "y", "value": 5077 },
        { "property": "yMod", "value": 0 },
        { "property": "yModType", "value": "none" },
        { "property": "yIter", "value": -151 },
        { "property": "yIterFunc", "value": "none" },
        { "property": "yr", "value": 0 },
        { "property": "yrMod", "value": 0 },
        { "property": "yrModType", "value": "none" },
        { "property": "yrIter", "value": 0 },
        { "property": "yrIterFunc", "value": "none" },
        { "property": "z", "value": 0 },
        { "property": "zMod", "value": 0 },
        { "property": "zModType", "value": "none" },
        { "property": "zIter", "value": -2947 },
        { "property": "zIterFunc", "value": "none" },
        { "property": "zr", "value": 0 },
        { "property": "zrMod", "value": 0 },
        { "property": "zrModType", "value": "none" },
        { "property": "zrIter", "value": 0 },
        { "property": "zrIterFunc", "value": "none" },
        { "property": "w", "value": 50000 },
        { "property": "wMod", "value": 0 },
        { "property": "wModType", "value": "none" },
        { "property": "wIter", "value": 8200 },
        { "property": "wIterFunc", "value": "none" },
        { "property": "h", "value": 9800 },
        { "property": "hMod", "value": 0 },
        { "property": "hModType", "value": "none" },
        { "property": "hIter", "value": 0 },
        { "property": "hIterFunc", "value": "none" },
        { "property": "l", "value": 0 },
        { "property": "lMod", "value": 0 },
        { "property": "lModType", "value": "none" },
        { "property": "lIter", "value": 0 },
        { "property": "lIterFunc", "value": "none" },
        { "property": "s", "value": 1476 },
        { "property": "sMod", "value": 0 },
        { "property": "sModType", "value": "none" },
        { "property": "sIter", "value": 0 },
        { "property": "sIterFunc", "value": "none" },
        { "property": "strokeColor", "value": -15507354 },
        { "property": "strokeColorMod", "value": 0 },
        { "property": "strokeColorModType", "value": "none" },
        { "property": "strokeColorIter", "value": 0 },
        { "property": "strokeColorIterFunc", "value": "none" },
        { "property": "strokeWeight", "value": 2 },
        { "property": "strokeWeightMod", "value": 0 },
        { "property": "strokeWeightModType", "value": "none" },
        { "property": "strokeWeightIter", "value": 0 },
        { "property": "strokeWeightIterFunc", "value": "none" },
        { "property": "fillColor", "value": -1532656 },
        { "property": "fillColorMod", "value": 0 },
        { "property": "fillColorModType", "value": "none" },
        { "property": "fillColorIter", "value": 0 },
        { "property": "fillColorIterFunc", "value": "none" },
        { "property": "paramA", "value": 50 },
        { "property": "paramAMod", "value": 0 },
        { "property": "paramAModType", "value": "none" },
        { "property": "paramAIter", "value": 0 },
        { "property": "paramAIterFunc", "value": "none" },
        { "property": "paramB", "value": 162 },
        { "property": "paramBMod", "value": 0 },
        { "property": "paramBModType", "value": "none" },
        { "property": "paramBIter", "value": 200 },
        { "property": "paramBIterFunc", "value": "none" },
        { "property": "paramC", "value": 100 },
        { "property": "paramCMod", "value": 0 },
        { "property": "paramCModType", "value": "none" },
        { "property": "paramCIter", "value": 285 },
        { "property": "paramCIterFunc", "value": "none" },
        { "property": "paramD", "value": 50 },
        { "property": "paramDMod", "value": 0 },
        { "property": "paramDModType", "value": "none" },
        { "property": "paramDIter", "value": 40 },
        { "property": "paramDIterFunc", "value": "none" },
        { "property": "paramE", "value": 0 },
        { "property": "paramEMod", "value": 0 },
        { "property": "paramEModType", "value": "none" },
        { "property": "paramEIter", "value": 0 },
        { "property": "paramEIterFunc", "value": "none" },
        { "property": "modDelay", "value": 0 },
        { "property": "variation", "value": "none" },
        { "property": "i", "value": 15 }
      ]
    },
    {
      "name": "Circle_test",
      "shape": "Circle",
      "properties": [
        { "property": "x", "value": -15103 },
        { "property": "xMod", "value": 0 },
        { "property": "xModType", "value": "none" },
        { "property": "xIter", "value": 40711 },
        { "property": "xIterFunc", "value": "sin(x)" },
        { "property": "xr", "value": 90 },
        { "property": "xrMod", "value": 0 },
        { "property": "xrModType", "value": "none" },
        { "property": "xrIter", "value": 0 },
        { "property": "xrIterFunc", "value": "none" },
        { "property": "y", "value": -4450 },
        { "property": "yMod", "value": 0 },
        { "property": "yModType", "value": "none" },
        { "property": "yIter", "value": 400 },
        { "property": "yIterFunc", "value": "random 100" },
        { "property": "yr", "value": 0 },
        { "property": "yrMod", "value": 0 },
        { "property": "yrModType", "value": "none" },
        { "property": "yrIter", "value": 0 },
        { "property": "yrIterFunc", "value": "none" },
        { "property": "z", "value": -46000 },
        { "property": "zMod", "value": 0 },
        { "property": "zModType", "value": "none" },
        { "property": "zIter", "value": 510 },
        { "property": "zIterFunc", "value": "none" },
        { "property": "zr", "value": 45 },
        { "property": "zrMod", "value": 0 },
        { "property": "zrModType", "value": "none" },
        { "property": "zrIter", "value": 10 },
        { "property": "zrIterFunc", "value": "none" },
        { "property": "w", "value": 701 },
        { "property": "wMod", "value": 0 },
        { "property": "wModType", "value": "none" },
        { "property": "wIter", "value": 0 },
        { "property": "wIterFunc", "value": "none" },
        { "property": "h", "value": 600 },
        { "property": "hMod", "value": 0 },
        { "property": "hModType", "value": "none" },
        { "property": "hIter", "value": 0 },
        { "property": "hIterFunc", "value": "none" },
        { "property": "l", "value": 10000 },
        { "property": "lMod", "value": 0 },
        { "property": "lModType", "value": "none" },
        { "property": "lIter", "value": -800 },
        { "property": "lIterFunc", "value": "random 100" },
        { "property": "s", "value": 100 },
        { "property": "sMod", "value": 0 },
        { "property": "sModType", "value": "none" },
        { "property": "sIter", "value": 0 },
        { "property": "sIterFunc", "value": "none" },
        { "property": "strokeColor", "value": -2405597 },
        { "property": "strokeColorMod", "value": 0 },
        { "property": "strokeColorModType", "value": "none" },
        { "property": "strokeColorIter", "value": 0 },
        { "property": "strokeColorIterFunc", "value": "none" },
        { "property": "strokeWeight", "value": 2 },
        { "property": "strokeWeightMod", "value": 0 },
        { "property": "strokeWeightModType", "value": "none" },
        { "property": "strokeWeightIter", "value": 0 },
        { "property": "strokeWeightIterFunc", "value": "none" },
        { "property": "fillColor", "value": -13096668 },
        { "property": "fillColorMod", "value": 0 },
        { "property": "fillColorModType", "value": "none" },
        { "property": "fillColorIter", "value": 0 },
        { "property": "fillColorIterFunc", "value": "none" },
        { "property": "paramA", "value": 0 },
        { "property": "paramAMod", "value": 0 },
        { "property": "paramAModType", "value": "none" },
        { "property": "paramAIter", "value": 0 },
        { "property": "paramAIterFunc", "value": "none" },
        { "property": "paramB", "value": 0 },
        { "property": "paramBMod", "value": 0 },
        { "property": "paramBModType", "value": "none" },
        { "property": "paramBIter", "value": 0 },
        { "property": "paramBIterFunc", "value": "none" },
        { "property": "paramC", "value": 0 },
        { "property": "paramCMod", "value": 0 },
        { "property": "paramCModType", "value": "none" },
        { "property": "paramCIter", "value": 0 },
        { "property": "paramCIterFunc", "value": "none" },
        { "property": "paramD", "value": 0 },
        { "property": "paramDMod", "value": 0 },
        { "property": "paramDModType", "value": "none" },
        { "property": "paramDIter", "value": 0 },
        { "property": "paramDIterFunc", "value": "none" },
        { "property": "paramE", "value": 0 },
        { "property": "paramEMod", "value": 0 },
        { "property": "paramEModType", "value": "none" },
        { "property": "paramEIter", "value": 0 },
        { "property": "paramEIterFunc", "value": "none" },
        { "property": "modDelay", "value": 0 },
        { "property": "variation", "value": "none" },
        { "property": "i", "value": 29 }
      ]
    },
  ],
  "colors": {
    "background": {
      "int": -2048386,
      "value": "#E0BE7E"
    },
    "accentA": {
      "int": -2405597,
      "value": "#DB4B23"
    },
    "accentB": {
      "int": -13096668,
      "value": "#382924"
    },
    "accentC": {
      "int": -1532656,
      "value": "#E89D10"
    },
    "accentD": {
      "int": -15507354,
      "value": "#136066"
    }
  },
  "id": "0000X",
  "name": "example"
}

export const EXAMPLE_CUSTOMIZATIONS = [
  { property: 'y', from: 0, to: 5077 },
  { property: 'yIter', from: 0, to: -151 },
  { property: 'zIter', from: 0, to: -2947 },
  { property: 'w', from: 100, to: 50000 },
  { property: 'wIter', from: 0, to: 8200 },
  { property: 'h', from: 100, to: 9800 },
  { property: 's', from: 0, to: 1476 },
  { property: 'strokeColor', from: -1, to: -15507354 },
  { property: 'fillColor', from: -16777216, to: -1532656 },
  { property: 'paramA', from: 0, to: 50 },
  { property: 'paramB', from: 0, to: 162 },
  { property: 'paramBIter', from: 0, to: 200 },
  { property: 'paramC', from: 0, to: 100 },
  { property: 'paramCIter', from: 0, to: 285 },
  { property: 'paramD', from: 0, to: 50 },
  { property: 'paramDIter', from: 0, to: 40 },
  { property: 'i', from: 1, to: 15 }
]

export const EXAMPLE_COLOR_PROPERTY_PAIR = { property: 'strokeColor', from: -1, to: -15507354 }
export const EXAMPLE_ITER_FUNC_PROPERTY_PAIR = { property: 'xIterFunc', from: 'none', to: 'sin(x)' }

export const EXAMPLE_SEQUENCE = [
  0,
  3000,
  3200,
  3345,
  3520,
  3690,
  3865,
  4039,
  4200,
  4385,
  4560,
  5000,
  4600,
  5270,
  5077
]

export const EXAMPLE_PALETTE = [
  -2048386,
  -2405597,
  -13096668,
  -1532656,
  -15507354
]

export const EXAMPLE_PALETTE_SEQUENCE = [
  -1,
  -13096668,
  -15507354,
  -2405597,
  -13096668,
  -2048386,
  -1532656,
  -15507354,
]

export const EXAMPLE_ITER_FUNC_SEQUENCE = [
  'none',
  'x*(x/10)',
  'random 100',
  'x/3',
  'x/4',
  'x/2',
  '1/x',
  'sin(x)'
]

export const IGNORED_PROPERTIES = []

export const EXAMPLE_ANIMATION_VALUES = [
  0,
  0.1111111111111111,
  0.2222222222222222,
  0.3333333333333333,
  0.4444444444444444,
  0.5555555555555556,
  0.6666666666666666,
  0.7777777777777778,
  0.8888888888888888,
  1
]

export const EXAMPLE_ANIMATION_VALUES_EASE_IN_QUAD = [
  0,
  0.0011890606420927466,
  0.0047562425683709865,
  0.01070154577883472,
  0.019024970273483946,
  0.02972651605231867,
  0.04280618311533888,
  0.0582639714625446,
  0.07609988109393578,
  0.09631391200951249,
  0.11890606420927469,
  0.14387633769322233,
  0.17122473246135553,
  0.2009512485136742,
  0.2330558858501784,
  0.26753864447086806,
  0.30439952437574314,
  0.34363852556480373,
  0.38525564803804996,
  0.42925089179548154,
  0.47562425683709875,
  0.5243757431629014,
  0.5755053507728893,
  0.6290130796670631,
  0.6848989298454221,
  0.7431629013079666,
  0.8038049940546969,
  0.8668252080856124,
  0.9322235434007136,
  1
]
