export const OAVP_OBJECT_PROPERTIES = [
  { id: "x", defaultValue: 0, type: "int" },
  { id: "xMod", defaultValue: 0.0, type: "float" },
  { id: "xModType", defaultValue: "none", type: "String" },
  { id: "xIter", defaultValue: 0.0, type: "float" },
  { id: "xIterFunc", defaultValue: "none", type: "String" },
  { id: "xr", defaultValue: 0, type: "int" },
  { id: "xrMod", defaultValue: 0.0, type: "float" },
  { id: "xrModType", defaultValue: "none", type: "String" },
  { id: "xrIter", defaultValue: 0.0, type: "float" },
  { id: "xrIterFunc", defaultValue: "none", type: "String" },
  { id: "y", defaultValue: 0, type: "int" },
  { id: "yMod", defaultValue: 0.0, type: "float" },
  { id: "yModType", defaultValue: "none", type: "String" },
  { id: "yIter", defaultValue: 0.0, type: "float" },
  { id: "yIterFunc", defaultValue: "none", type: "String" },
  { id: "yr", defaultValue: 0, type: "int" },
  { id: "yrMod", defaultValue: 0.0, type: "float" },
  { id: "yrModType", defaultValue: "none", type: "String" },
  { id: "yrIter", defaultValue: 0.0, type: "float" },
  { id: "yrIterFunc", defaultValue: "none", type: "String" },
  { id: "z", defaultValue: 0, type: "int" },
  { id: "zMod", defaultValue: 0.0, type: "float" },
  { id: "zModType", defaultValue: "none", type: "String" },
  { id: "zIter", defaultValue: 0.0, type: "float" },
  { id: "zIterFunc", defaultValue: "none", type: "String" },
  { id: "zr", defaultValue: 0, type: "int" },
  { id: "zrMod", defaultValue: 0.0, type: "float" },
  { id: "zrModType", defaultValue: "none", type: "String" },
  { id: "zrIter", defaultValue: 0.0, type: "float" },
  { id: "zrIterFunc", defaultValue: "none", type: "String" },
  { id: "w", defaultValue: 0.0, type: "float" },
  { id: "wMod", defaultValue: 0.0, type: "float" },
  { id: "wModType", defaultValue: "none", type: "String" },
  { id: "wIter", defaultValue: 0.0, type: "float" },
  { id: "wIterFunc", defaultValue: "none", type: "String" },
  { id: "h", defaultValue: 0.0, type: "float" },
  { id: "hMod", defaultValue: 0.0, type: "float" },
  { id: "hModType", defaultValue: "none", type: "String" },
  { id: "hIter", defaultValue: 0.0, type: "float" },
  { id: "hIterFunc", defaultValue: "none", type: "String" },
  { id: "l", defaultValue: 0.0, type: "float" },
  { id: "lMod", defaultValue: 0.0, type: "float" },
  { id: "lModType", defaultValue: "none", type: "String" },
  { id: "lIter", defaultValue: 0.0, type: "float" },
  { id: "lIterFunc", defaultValue: "none", type: "String" },
  { id: "s", defaultValue: 0.0, type: "float" },
  { id: "sMod", defaultValue: 0.0, type: "float" },
  { id: "sModType", defaultValue: "none", type: "String" },
  { id: "sIter", defaultValue: 0.0, type: "float" },
  { id: "sIterFunc", defaultValue: "none", type: "String" },
  { id: "strokeColor", defaultValue: -1, type: "color" },
  { id: "strokeColorMod", defaultValue: 0.0, type: "float" },
  { id: "strokeColorModType", defaultValue: "none", type: "String" },
  { id: "strokeColorIter", defaultValue: 0.0, type: "float" },
  { id: "strokeColorIterFunc", defaultValue: "none", type: "String" },
  { id: "strokeWeight", defaultValue: 2.0, type: "float" },
  { id: "strokeWeightMod", defaultValue: 0.0, type: "float" },
  { id: "strokeWeightModType", defaultValue: "none", type: "String" },
  { id: "strokeWeightIter", defaultValue: 0.0, type: "float" },
  { id: "strokeWeightIterFunc", defaultValue: "none", type: "String" },
  { id: "fillColor", defaultValue: -16777216, type: "color" },
  { id: "fillColorMod", defaultValue: 0.0, type: "float" },
  { id: "fillColorModType", defaultValue: "none", type: "String" },
  { id: "fillColorIter", defaultValue: 0.0, type: "float" },
  { id: "fillColorIterFunc", defaultValue: "none", type: "String" },
  { id: "paramA", defaultValue: 0.0, type: "float" },
  { id: "paramAMod", defaultValue: 0.0, type: "float" },
  { id: "paramAModType", defaultValue: "none", type: "String" },
  { id: "paramAIter", defaultValue: 0.0, type: "float" },
  { id: "paramAIterFunc", defaultValue: "none", type: "String" },
  { id: "paramB", defaultValue: 0.0, type: "float" },
  { id: "paramBMod", defaultValue: 0.0, type: "float" },
  { id: "paramBModType", defaultValue: "none", type: "String" },
  { id: "paramBIter", defaultValue: 0.0, type: "float" },
  { id: "paramBIterFunc", defaultValue: "none", type: "String" },
  { id: "paramC", defaultValue: 0.0, type: "float" },
  { id: "paramCMod", defaultValue: 0.0, type: "float" },
  { id: "paramCModType", defaultValue: "none", type: "String" },
  { id: "paramCIter", defaultValue: 0.0, type: "float" },
  { id: "paramCIterFunc", defaultValue: "none", type: "String" },
  { id: "paramD", defaultValue: 0.0, type: "float" },
  { id: "paramDMod", defaultValue: 0.0, type: "float" },
  { id: "paramDModType", defaultValue: "none", type: "String" },
  { id: "paramDIter", defaultValue: 0.0, type: "float" },
  { id: "paramDIterFunc", defaultValue: "none", type: "String" },
  { id: "paramE", defaultValue: 0.0, type: "float" },
  { id: "paramEMod", defaultValue: 0.0, type: "float" },
  { id: "paramEModType", defaultValue: "none", type: "String" },
  { id: "paramEIter", defaultValue: 0.0, type: "float" },
  { id: "paramEIterFunc", defaultValue: "none", type: "String" },
  { id: "modDelay", defaultValue: 0, type: "int" },
  { id: "variation", defaultValue: "none", type: "String" },
  { id: "i", defaultValue: 1, type: "int" },
];

export const OAVP_AVAILABLE_SHAPES = [
  "Arc",
  "Box",
  "Bullseye",
  "Circle",
  "CurvedLine",
  "Flatbox",
  "GoldenRatio",
  "Gradient",
  "GridInterval",
  "Line",
  "Orbital",
  "Pyramid",
  "RadialSpectrum",
  "Rectangle",
  "Shader",
  "Spectrum",
  "SpectrumMesh",
  "Sphere",
  "Splash",
  "Terrain",
  "Triangle",
  "Vegetation",
  "Waveform",
  "ZRectangles",
];

export const SINGLE_LINE_PARAMETER_SET_DELIMITER = "&";
export const OBJECT_NAME_AND_PROPERTIES_DELIMITER = "|";
export const OBJECT_NAME_AND_TAGS_DELIMITER = "_";
export const SKETCH_WEBSOCKET_SERVER_URL = "ws://localhost:6287/commands";
export const WEBSERVER_PORT = 3001;
export const COMMANDER_WEBSOCKET_SERVER_PORT = 3002;
export const DIRECTORY_PATH = "./";
export const TARGET_FILE_NAME = "target.txt";
export const DUMP_FILE_PATH = "preset-dump.txt";
export const EXPORT_FILE_NAME = "export.txt";
export const EXPORT_IMAGE_NAME = "export.png";
export const EXPORT_FILE_DIR = "../../exports";
export const GENOBJ_FILE_NAME = "genobj.json";
export const IMAGE_COPY_TIMEOUT_DURATION = 500;
export const FILE_COPY_TIMEOUT_DURATION = 500;
export const OVERRIDE_VALUES_DELIMITER = ";";
export const PROPERTY_VALUE_DELIMITER = ":";
export const OBJECT_NAME_REGEX = /\.add\("[^"]+","([^"]+)"\)/;
export const OBJECT_NAME_AND_SHAPE_REGEX = /objects\.add\("([^"]+)",\s*"([^"]+)"\)/;
export const OBJECT_PROPERTIES_REGEX = /\.set\("([^"]+)",\s*([^)]+)\)/g;
export const OBJECT_PROPERTY_KEY_AND_VALUE_REGEX = /\("([^"]+)","?([^"]+)"?\)/;
export const COLOR_EXTRACTION_REGEX = /\((-?\d+)\)/;

export const INVALID_TAGS = [
  'nofill',
  'nostroke',
  'backgroundstroke',
  'notbackgroundstroke',
  'accentastroke',
  'notaccentastroke',
  'accentbstroke',
  'notaccentbstroke',
  'accentcstroke',
  'notaccentcstroke',
  'accentdstroke',
  'notaccentdstroke',
  'backgroundfill',
  'notbackgroundfill',
  'accentafill',
  'notaccentafill',
  'accentbfill',
  'notaccentbfill',
  'accentcfill',
  'notaccentcfill',
  'accentdfill',
  'notaccentdfill',
  'accenta',
  'accentb',
  'accentc',
  'accentd',
  'accente',
  'main',
  'background',
  'camera',
  'left',
  'right',
  'middle',
  'a 1',
  'a 2',
  'a 3',
  'b 1',
  'b 2',
  'b 3',
  'c 1',
  'c 2',
  'c 3',
  'a',
  'b'
]
