export const EXAMPLE_SKETCH_FILE = `
//GENOBJ:[{"oavpObject":"Rectangle","params":[{"id":"y","value":40000,"eval":"40000","type":"int"},{"id":"z","value":-65000,"eval":"-65000","type":"int"},{"id":"w","value":200000,"eval":"200000.0","type":"float"},{"id":"h","value":80000,"eval":"80000.0","type":"float"}],"id":"Rectangle_horizon_accentafill_3QgpWVUAZ"}]
//DATE:Tue Jan 23 22:06:22 EST 2024
//PALETTE:#9E9E9E,#5ECDE0,#00FFF2,#C4FFC9,#E0E0E0
//SEED:26
void setupSketch() {
setSketchSeed(26);
objects.add("background", "OavpObject").set("x",0).set("xMod",0.0).set("xModType","none").set("xIter",0.0).set("xIterFunc","none").set("xr",0).set("xrMod",0.0).set("xrModType","none").set("xrIter",0.0).set("xrIterFunc","none").set("y",0).set("yMod",0.0).set("yModType","none").set("yIter",0.0).set("yIterFunc","none").set("yr",0).set("yrMod",0.0).set("yrModType","none").set("yrIter",0.0).set("yrIterFunc","none").set("z",0).set("zMod",0.0).set("zModType","none").set("zIter",0.0).set("zIterFunc","none").set("zr",0).set("zrMod",0.0).set("zrModType","none").set("zrIter",0.0).set("zrIterFunc","none").set("w",100.0).set("wMod",0.0).set("wModType","none").set("wIter",0.0).set("wIterFunc","none").set("h",100.0).set("hMod",0.0).set("hModType","none").set("hIter",0.0).set("hIterFunc","none").set("l",0.0).set("lMod",0.0).set("lModType","none").set("lIter",0.0).set("lIterFunc","none").set("s",100.0).set("sMod",0.0).set("sModType","none").set("sIter",0.0).set("sIterFunc","none").set("strokeColor",-2039584).set("strokeColorMod",0.0).set("strokeColorModType","none").set("strokeColorIter",0.0).set("strokeColorIterFunc","none").set("strokeWeight",2.0).set("strokeWeightMod",0.0).set("strokeWeightModType","none").set("strokeWeightIter",0.0).set("strokeWeightIterFunc","none").set("fillColor",-10564128).set("fillColorMod",0.0).set("fillColorModType","none").set("fillColorIter",0.0).set("fillColorIterFunc","none").set("paramA",0.0).set("paramAMod",0.0).set("paramAModType","none").set("paramAIter",0.0).set("paramAIterFunc","none").set("paramB",0.0).set("paramBMod",0.0).set("paramBModType","none").set("paramBIter",0.0).set("paramBIterFunc","none").set("paramC",0.0).set("paramCMod",0.0).set("paramCModType","none").set("paramCIter",0.0).set("paramCIterFunc","none").set("paramD",0.0).set("paramDMod",0.0).set("paramDModType","none").set("paramDIter",0.0).set("paramDIterFunc","none").set("paramE",0.0).set("paramEMod",0.0).set("paramEModType","none").set("paramEIter",0.0).set("paramEIterFunc","none").set("modDelay",0).set("i",1);
objects.add("Rectangle_horizon_accentafill_3QgpWVUAZ", "Rectangle").set("x",0).set("xMod",0.0).set("xModType","none").set("xIter",0.0).set("xIterFunc","none").set("xr",0).set("xrMod",0.0).set("xrModType","none").set("xrIter",0.0).set("xrIterFunc","none").set("y",40000).set("yMod",0.0).set("yModType","none").set("yIter",0.0).set("yIterFunc","none").set("yr",0).set("yrMod",0.0).set("yrModType","none").set("yrIter",0.0).set("yrIterFunc","none").set("z",-65000).set("zMod",0.0).set("zModType","none").set("zIter",0.0).set("zIterFunc","none").set("zr",0).set("zrMod",0.0).set("zrModType","none").set("zrIter",0.0).set("zrIterFunc","none").set("w",200000.0).set("wMod",0.0).set("wModType","none").set("wIter",0.0).set("wIterFunc","none").set("h",80000.0).set("hMod",0.0).set("hModType","none").set("hIter",0.0).set("hIterFunc","none").set("l",0.0).set("lMod",0.0).set("lModType","none").set("lIter",0.0).set("lIterFunc","none").set("s",0.0).set("sMod",0.0).set("sModType","none").set("sIter",0.0).set("sIterFunc","none").set("strokeColor",-10564128).set("strokeColorMod",0.0).set("strokeColorModType","none").set("strokeColorIter",0.0).set("strokeColorIterFunc","none").set("strokeWeight",2.0).set("strokeWeightMod",0.0).set("strokeWeightModType","none").set("strokeWeightIter",0.0).set("strokeWeightIterFunc","none").set("fillColor",-3866679).set("fillColorMod",0.0).set("fillColorModType","none").set("fillColorIter",0.0).set("fillColorIterFunc","none").set("paramA",0.0).set("paramAMod",0.0).set("paramAModType","none").set("paramAIter",0.0).set("paramAIterFunc","none").set("paramB",0.0).set("paramBMod",0.0).set("paramBModType","none").set("paramBIter",0.0).set("paramBIterFunc","none").set("paramC",0.0).set("paramCMod",0.0).set("paramCModType","none").set("paramCIter",0.0).set("paramCIterFunc","none").set("paramD",0.0).set("paramDMod",0.0).set("paramDModType","none").set("paramDIter",0.0).set("paramDIterFunc","none").set("paramE",0.0).set("paramEMod",0.0).set("paramEModType","none").set("paramEIter",0.0).set("paramEIterFunc","none").set("modDelay",0).set("i",1);
objects.add("camera", "OavpObject").set("x",0).set("xMod",0.0).set("xModType","none").set("xIter",0.0).set("xIterFunc","none").set("xr",0).set("xrMod",0.0).set("xrModType","none").set("xrIter",0.0).set("xrIterFunc","none").set("y",0).set("yMod",0.0).set("yModType","none").set("yIter",0.0).set("yIterFunc","none").set("yr",0).set("yrMod",0.0).set("yrModType","none").set("yrIter",0.0).set("yrIterFunc","none").set("z",0).set("zMod",0.0).set("zModType","none").set("zIter",0.0).set("zIterFunc","none").set("zr",0).set("zrMod",0.0).set("zrModType","none").set("zrIter",0.0).set("zrIterFunc","none").set("w",0.0).set("wMod",0.0).set("wModType","none").set("wIter",0.0).set("wIterFunc","none").set("h",0.0).set("hMod",0.0).set("hModType","none").set("hIter",0.0).set("hIterFunc","none").set("l",0.0).set("lMod",0.0).set("lModType","none").set("lIter",0.0).set("lIterFunc","none").set("s",100.0).set("sMod",0.0).set("sModType","none").set("sIter",0.0).set("sIterFunc","none").set("strokeColor",-2039584).set("strokeColorMod",0.0).set("strokeColorModType","none").set("strokeColorIter",0.0).set("strokeColorIterFunc","none").set("strokeWeight",2.0).set("strokeWeightMod",0.0).set("strokeWeightModType","none").set("strokeWeightIter",0.0).set("strokeWeightIterFunc","none").set("fillColor",-16711694).set("fillColorMod",0.0).set("fillColorModType","none").set("fillColorIter",0.0).set("fillColorIterFunc","none").set("paramA",100000.0).set("paramAMod",0.0).set("paramAModType","none").set("paramAIter",0.0).set("paramAIterFunc","none").set("paramB",0.0).set("paramBMod",0.0).set("paramBModType","none").set("paramBIter",0.0).set("paramBIterFunc","none").set("paramC",0.0).set("paramCMod",0.0).set("paramCModType","none").set("paramCIter",0.0).set("paramCIterFunc","none").set("paramD",0.0).set("paramDMod",0.0).set("paramDModType","none").set("paramDIter",0.0).set("paramDIterFunc","none").set("paramE",0.0).set("paramEMod",0.0).set("paramEModType","none").set("paramEIter",0.0).set("paramEIterFunc","none").set("modDelay",0).set("i",1);
}
void setupSketchPostEditor() {
editor.setPaletteByArrayString("#9E9E9E,#5ECDE0,#00FFF2,#C4FFC9,#E0E0E0");
editor.setBackgroundColor(-10564128);
editor.setAccentA(-3866679);
editor.setAccentB(-6381922);
editor.setAccentC(-2039584);
editor.setAccentD(-16711694);
}
void updateSketch() {}
void drawSketch() {}
`

export const EXAMPLE_SKETCH_DATA_OBJECT = {
  "date": "Tue Jan 23 22:06:22 EST 2024",
  "seed": 26,
  "colors": {
    "background": {
      "int": -10564128,
      "value": "#5ECDE0"
    },
    "accentA": {
      "int": -3866679,
      "value": "#C4FFC9"
    },
    "accentB": {
      "int": -6381922,
      "value": "#9E9E9E"
    },
    "accentC": {
      "int": -2039584,
      "value": "#E0E0E0"
    },
    "accentD": {
      "int": -16711694,
      "value": "#00FFF2"
    }
  },
  "tags": [
    "horizon"
  ],
  "objects": [
    {
      "name": "background",
      "shape": "OavpObject",
      "properties": [
        { "property": "x", "value": 0 },
        { "property": "xMod", "value": 0 },
        { "property": "xModType", "value": "none" },
        { "property": "xIter", "value": 0 },
        { "property": "xIterFunc", "value": "none" },
        { "property": "xr", "value": 0 },
        { "property": "xrMod", "value": 0 },
        { "property": "xrModType", "value": "none" },
        { "property": "xrIter", "value": 0 },
        { "property": "xrIterFunc", "value": "none" },
        { "property": "y", "value": 0 },
        { "property": "yMod", "value": 0 },
        { "property": "yModType", "value": "none" },
        { "property": "yIter", "value": 0 },
        { "property": "yIterFunc", "value": "none" },
        { "property": "yr", "value": 0 },
        { "property": "yrMod", "value": 0 },
        { "property": "yrModType", "value": "none" },
        { "property": "yrIter", "value": 0 },
        { "property": "yrIterFunc", "value": "none" },
        { "property": "z", "value": 0 },
        { "property": "zMod", "value": 0 },
        { "property": "zModType", "value": "none" },
        { "property": "zIter", "value": 0 },
        { "property": "zIterFunc", "value": "none" },
        { "property": "zr", "value": 0 },
        { "property": "zrMod", "value": 0 },
        { "property": "zrModType", "value": "none" },
        { "property": "zrIter", "value": 0 },
        { "property": "zrIterFunc", "value": "none" },
        { "property": "w", "value": 100 },
        { "property": "wMod", "value": 0 },
        { "property": "wModType", "value": "none" },
        { "property": "wIter", "value": 0 },
        { "property": "wIterFunc", "value": "none" },
        { "property": "h", "value": 100 },
        { "property": "hMod", "value": 0 },
        { "property": "hModType", "value": "none" },
        { "property": "hIter", "value": 0 },
        { "property": "hIterFunc", "value": "none" },
        { "property": "l", "value": 0 },
        { "property": "lMod", "value": 0 },
        { "property": "lModType", "value": "none" },
        { "property": "lIter", "value": 0 },
        { "property": "lIterFunc", "value": "none" },
        { "property": "s", "value": 100 },
        { "property": "sMod", "value": 0 },
        { "property": "sModType", "value": "none" },
        { "property": "sIter", "value": 0 },
        { "property": "sIterFunc", "value": "none" },
        { "property": "strokeColor", "value": -2039584 },
        { "property": "strokeColorMod", "value": 0 },
        { "property": "strokeColorModType", "value": "none" },
        { "property": "strokeColorIter", "value": 0 },
        { "property": "strokeColorIterFunc", "value": "none" },
        { "property": "strokeWeight", "value": 2 },
        { "property": "strokeWeightMod", "value": 0 },
        { "property": "strokeWeightModType", "value": "none" },
        { "property": "strokeWeightIter", "value": 0 },
        { "property": "strokeWeightIterFunc", "value": "none" },
        { "property": "fillColor", "value": -10564128 },
        { "property": "fillColorMod", "value": 0 },
        { "property": "fillColorModType", "value": "none" },
        { "property": "fillColorIter", "value": 0 },
        { "property": "fillColorIterFunc", "value": "none" },
        { "property": "paramA", "value": 0 },
        { "property": "paramAMod", "value": 0 },
        { "property": "paramAModType", "value": "none" },
        { "property": "paramAIter", "value": 0 },
        { "property": "paramAIterFunc", "value": "none" },
        { "property": "paramB", "value": 0 },
        { "property": "paramBMod", "value": 0 },
        { "property": "paramBModType", "value": "none" },
        { "property": "paramBIter", "value": 0 },
        { "property": "paramBIterFunc", "value": "none" },
        { "property": "paramC", "value": 0 },
        { "property": "paramCMod", "value": 0 },
        { "property": "paramCModType", "value": "none" },
        { "property": "paramCIter", "value": 0 },
        { "property": "paramCIterFunc", "value": "none" },
        { "property": "paramD", "value": 0 },
        { "property": "paramDMod", "value": 0 },
        { "property": "paramDModType", "value": "none" },
        { "property": "paramDIter", "value": 0 },
        { "property": "paramDIterFunc", "value": "none" },
        { "property": "paramE", "value": 0 },
        { "property": "paramEMod", "value": 0 },
        { "property": "paramEModType", "value": "none" },
        { "property": "paramEIter", "value": 0 },
        { "property": "paramEIterFunc", "value": "none" },
        { "property": "modDelay", "value": 0 },
        { "property": "i", "value": 1 }
      ]
    },
    {
      "name": "Rectangle_horizon_accentafill_3QgpWVUAZ",
      "shape": "Rectangle",
      "properties": [
        { "property": "x", "value": 0 },
        { "property": "xMod", "value": 0 },
        { "property": "xModType", "value": "none" },
        { "property": "xIter", "value": 0 },
        { "property": "xIterFunc", "value": "none" },
        { "property": "xr", "value": 0 },
        { "property": "xrMod", "value": 0 },
        { "property": "xrModType", "value": "none" },
        { "property": "xrIter", "value": 0 },
        { "property": "xrIterFunc", "value": "none" },
        { "property": "y", "value": 40000 },
        { "property": "yMod", "value": 0 },
        { "property": "yModType", "value": "none" },
        { "property": "yIter", "value": 0 },
        { "property": "yIterFunc", "value": "none" },
        { "property": "yr", "value": 0 },
        { "property": "yrMod", "value": 0 },
        { "property": "yrModType", "value": "none" },
        { "property": "yrIter", "value": 0 },
        { "property": "yrIterFunc", "value": "none" },
        { "property": "z", "value": -65000 },
        { "property": "zMod", "value": 0 },
        { "property": "zModType", "value": "none" },
        { "property": "zIter", "value": 0 },
        { "property": "zIterFunc", "value": "none" },
        { "property": "zr", "value": 0 },
        { "property": "zrMod", "value": 0 },
        { "property": "zrModType", "value": "none" },
        { "property": "zrIter", "value": 0 },
        { "property": "zrIterFunc", "value": "none" },
        { "property": "w", "value": 200000 },
        { "property": "wMod", "value": 0 },
        { "property": "wModType", "value": "none" },
        { "property": "wIter", "value": 0 },
        { "property": "wIterFunc", "value": "none" },
        { "property": "h", "value": 80000 },
        { "property": "hMod", "value": 0 },
        { "property": "hModType", "value": "none" },
        { "property": "hIter", "value": 0 },
        { "property": "hIterFunc", "value": "none" },
        { "property": "l", "value": 0 },
        { "property": "lMod", "value": 0 },
        { "property": "lModType", "value": "none" },
        { "property": "lIter", "value": 0 },
        { "property": "lIterFunc", "value": "none" },
        { "property": "s", "value": 0 },
        { "property": "sMod", "value": 0 },
        { "property": "sModType", "value": "none" },
        { "property": "sIter", "value": 0 },
        { "property": "sIterFunc", "value": "none" },
        { "property": "strokeColor", "value": -10564128 },
        { "property": "strokeColorMod", "value": 0 },
        { "property": "strokeColorModType", "value": "none" },
        { "property": "strokeColorIter", "value": 0 },
        { "property": "strokeColorIterFunc", "value": "none" },
        { "property": "strokeWeight", "value": 2 },
        { "property": "strokeWeightMod", "value": 0 },
        { "property": "strokeWeightModType", "value": "none" },
        { "property": "strokeWeightIter", "value": 0 },
        { "property": "strokeWeightIterFunc", "value": "none" },
        { "property": "fillColor", "value": -3866679 },
        { "property": "fillColorMod", "value": 0 },
        { "property": "fillColorModType", "value": "none" },
        { "property": "fillColorIter", "value": 0 },
        { "property": "fillColorIterFunc", "value": "none" },
        { "property": "paramA", "value": 0 },
        { "property": "paramAMod", "value": 0 },
        { "property": "paramAModType", "value": "none" },
        { "property": "paramAIter", "value": 0 },
        { "property": "paramAIterFunc", "value": "none" },
        { "property": "paramB", "value": 0 },
        { "property": "paramBMod", "value": 0 },
        { "property": "paramBModType", "value": "none" },
        { "property": "paramBIter", "value": 0 },
        { "property": "paramBIterFunc", "value": "none" },
        { "property": "paramC", "value": 0 },
        { "property": "paramCMod", "value": 0 },
        { "property": "paramCModType", "value": "none" },
        { "property": "paramCIter", "value": 0 },
        { "property": "paramCIterFunc", "value": "none" },
        { "property": "paramD", "value": 0 },
        { "property": "paramDMod", "value": 0 },
        { "property": "paramDModType", "value": "none" },
        { "property": "paramDIter", "value": 0 },
        { "property": "paramDIterFunc", "value": "none" },
        { "property": "paramE", "value": 0 },
        { "property": "paramEMod", "value": 0 },
        { "property": "paramEModType", "value": "none" },
        { "property": "paramEIter", "value": 0 },
        { "property": "paramEIterFunc", "value": "none" },
        { "property": "modDelay", "value": 0 },
        { "property": "i", "value": 1 }
      ]
    },
    {
      "name": "camera",
      "shape": "OavpObject",
      "properties": [
        { "property": "x", "value": 0 },
        { "property": "xMod", "value": 0 },
        { "property": "xModType", "value": "none" },
        { "property": "xIter", "value": 0 },
        { "property": "xIterFunc", "value": "none" },
        { "property": "xr", "value": 0 },
        { "property": "xrMod", "value": 0 },
        { "property": "xrModType", "value": "none" },
        { "property": "xrIter", "value": 0 },
        { "property": "xrIterFunc", "value": "none" },
        { "property": "y", "value": 0 },
        { "property": "yMod", "value": 0 },
        { "property": "yModType", "value": "none" },
        { "property": "yIter", "value": 0 },
        { "property": "yIterFunc", "value": "none" },
        { "property": "yr", "value": 0 },
        { "property": "yrMod", "value": 0 },
        { "property": "yrModType", "value": "none" },
        { "property": "yrIter", "value": 0 },
        { "property": "yrIterFunc", "value": "none" },
        { "property": "z", "value": 0 },
        { "property": "zMod", "value": 0 },
        { "property": "zModType", "value": "none" },
        { "property": "zIter", "value": 0 },
        { "property": "zIterFunc", "value": "none" },
        { "property": "zr", "value": 0 },
        { "property": "zrMod", "value": 0 },
        { "property": "zrModType", "value": "none" },
        { "property": "zrIter", "value": 0 },
        { "property": "zrIterFunc", "value": "none" },
        { "property": "w", "value": 0 },
        { "property": "wMod", "value": 0 },
        { "property": "wModType", "value": "none" },
        { "property": "wIter", "value": 0 },
        { "property": "wIterFunc", "value": "none" },
        { "property": "h", "value": 0 },
        { "property": "hMod", "value": 0 },
        { "property": "hModType", "value": "none" },
        { "property": "hIter", "value": 0 },
        { "property": "hIterFunc", "value": "none" },
        { "property": "l", "value": 0 },
        { "property": "lMod", "value": 0 },
        { "property": "lModType", "value": "none" },
        { "property": "lIter", "value": 0 },
        { "property": "lIterFunc", "value": "none" },
        { "property": "s", "value": 100 },
        { "property": "sMod", "value": 0 },
        { "property": "sModType", "value": "none" },
        { "property": "sIter", "value": 0 },
        { "property": "sIterFunc", "value": "none" },
        { "property": "strokeColor", "value": -2039584 },
        { "property": "strokeColorMod", "value": 0 },
        { "property": "strokeColorModType", "value": "none" },
        { "property": "strokeColorIter", "value": 0 },
        { "property": "strokeColorIterFunc", "value": "none" },
        { "property": "strokeWeight", "value": 2 },
        { "property": "strokeWeightMod", "value": 0 },
        { "property": "strokeWeightModType", "value": "none" },
        { "property": "strokeWeightIter", "value": 0 },
        { "property": "strokeWeightIterFunc", "value": "none" },
        { "property": "fillColor", "value": -16711694 },
        { "property": "fillColorMod", "value": 0 },
        { "property": "fillColorModType", "value": "none" },
        { "property": "fillColorIter", "value": 0 },
        { "property": "fillColorIterFunc", "value": "none" },
        { "property": "paramA", "value": 100000 },
        { "property": "paramAMod", "value": 0 },
        { "property": "paramAModType", "value": "none" },
        { "property": "paramAIter", "value": 0 },
        { "property": "paramAIterFunc", "value": "none" },
        { "property": "paramB", "value": 0 },
        { "property": "paramBMod", "value": 0 },
        { "property": "paramBModType", "value": "none" },
        { "property": "paramBIter", "value": 0 },
        { "property": "paramBIterFunc", "value": "none" },
        { "property": "paramC", "value": 0 },
        { "property": "paramCMod", "value": 0 },
        { "property": "paramCModType", "value": "none" },
        { "property": "paramCIter", "value": 0 },
        { "property": "paramCIterFunc", "value": "none" },
        { "property": "paramD", "value": 0 },
        { "property": "paramDMod", "value": 0 },
        { "property": "paramDModType", "value": "none" },
        { "property": "paramDIter", "value": 0 },
        { "property": "paramDIterFunc", "value": "none" },
        { "property": "paramE", "value": 0 },
        { "property": "paramEMod", "value": 0 },
        { "property": "paramEModType", "value": "none" },
        { "property": "paramEIter", "value": 0 },
        { "property": "paramEIterFunc", "value": "none" },
        { "property": "modDelay", "value": 0 },
        { "property": "i", "value": 1 }
      ]
    }
  ],
  "generatorObject": [
    {
      "oavpObject": "Rectangle",
      "params":
      [
        {
          "id": "y",
          "value": 40000,
          "eval": "40000",
          "type": "int"
        },
        {
          "id": "z",
          "value": -65000,
          "eval": "-65000",
          "type": "int"
        },
        {
          "id": "w",
          "value": 200000,
          "eval": "200000.0",
          "type": "float"
        },
        {
          "id": "h",
          "value": 80000,
          "eval": "80000.0",
          "type": "float"
        }
      ],
      "id": "Rectangle_horizon_accentafill_3QgpWVUAZ"
    }
  ]
}
