export const EXAMPLE_SKETCH_FILE = `
//DATE:Sat Jan 20 00:17:17 EST 2024
//PALETTE:#288D85,#B9D9B4,#D18E8F,#B05574,#F0A991
//SEED:95
void setupSketch() {
setSketchSeed(95);
objects.add("Flatbox_city_main_accentastroke_accentbfill_RBui0TpNN0", "Flatbox").set("x",-11480).set("xMod",0.0).set("xModType","none").set("xIter",12600.0).set("xIterFunc","sin(x)").set("xr",90).set("xrMod",0.0).set("xrModType","none").set("xrIter",0.0).set("xrIterFunc","none").set("y",-4450).set("yMod",0.0).set("yModType","none").set("yIter",400.0).set("yIterFunc","random 100").set("yr",0).set("yrMod",0.0).set("yrModType","none").set("yrIter",0.0).set("yrIterFunc","none").set("z",-46000).set("zMod",0.0).set("zModType","none").set("zIter",548.0).set("zIterFunc","none").set("zr",45).set("zrMod",0.0).set("zrModType","none").set("zrIter",10.0).set("zrIterFunc","none").set("w",798.0).set("wMod",0.0).set("wModType","none").set("wIter",0.0).set("wIterFunc","none").set("h",600.0).set("hMod",0.0).set("hModType","none").set("hIter",0.0).set("hIterFunc","none").set("l",10000.0).set("lMod",0.0).set("lModType","none").set("lIter",-800.0).set("lIterFunc","random 100").set("s",100.0).set("sMod",0.0).set("sModType","none").set("sIter",0.0).set("sIterFunc","none").set("strokeColor",-5221004).set("strokeColorMod",0.0).set("strokeColorModType","none").set("strokeColorIter",0.0).set("strokeColorIterFunc","none").set("strokeWeight",2.0).set("strokeWeightMod",0.0).set("strokeWeightModType","none").set("strokeWeightIter",0.0).set("strokeWeightIterFunc","none").set("fillColor",-4597324).set("fillColorMod",0.0).set("fillColorModType","none").set("fillColorIter",0.0).set("fillColorIterFunc","none").set("paramA",0.0).set("paramAMod",0.0).set("paramAModType","none").set("paramAIter",0.0).set("paramAIterFunc","none").set("paramB",0.0).set("paramBMod",0.0).set("paramBModType","none").set("paramBIter",0.0).set("paramBIterFunc","none").set("paramC",0.0).set("paramCMod",0.0).set("paramCModType","none").set("paramCIter",0.0).set("paramCIterFunc","none").set("paramD",0.0).set("paramDMod",0.0).set("paramDModType","none").set("paramDIter",0.0).set("paramDIterFunc","none").set("paramE",0.0).set("paramEMod",0.0).set("paramEModType","none").set("paramEIter",0.0).set("paramEIterFunc","none").set("modDelay",0).set("i",46);
objects.add("Rectangle_fleet_lights_nostroke_accentcfill_4yYfI00iNI", "Rectangle").set("x",-15804).set("xMod",0.0).set("xModType","none").set("xIter",-6366.0).set("xIterFunc","none").set("xr",-4).set("xrMod",0.0).set("xrModType","none").set("xrIter",0.0).set("xrIterFunc","none").set("y",-26879).set("yMod",0.0).set("yModType","none").set("yIter",1785.0).set("yIterFunc","none").set("yr",14).set("yrMod",0.0).set("yrModType","none").set("yrIter",0.0).set("yrIterFunc","none").set("z",-86000).set("zMod",0.0).set("zModType","none").set("zIter",-3618.0).set("zIterFunc","none").set("zr",0).set("zrMod",0.0).set("zrModType","none").set("zrIter",0.0).set("zrIterFunc","none").set("w",8761.5).set("wMod",0.0).set("wModType","none").set("wIter",-4010.0).set("wIterFunc","none").set("h",500.0).set("hMod",0.0).set("hModType","none").set("hIter",-10.0).set("hIterFunc","none").set("l",5100.0).set("lMod",0.0).set("lModType","none").set("lIter",-10.0).set("lIterFunc","none").set("s",100.0).set("sMod",0.0).set("sModType","none").set("sIter",0.0).set("sIterFunc","none").set("strokeColor",0).set("strokeColorMod",0.0).set("strokeColorModType","none").set("strokeColorIter",0.0).set("strokeColorIterFunc","none").set("strokeWeight",2.0).set("strokeWeightMod",0.0).set("strokeWeightModType","none").set("strokeWeightIter",0.0).set("strokeWeightIterFunc","none").set("fillColor",-1005167).set("fillColorMod",0.0).set("fillColorModType","none").set("fillColorIter",0.0).set("fillColorIterFunc","none").set("paramA",0.0).set("paramAMod",0.0).set("paramAModType","none").set("paramAIter",0.0).set("paramAIterFunc","none").set("paramB",0.0).set("paramBMod",0.0).set("paramBModType","none").set("paramBIter",0.0).set("paramBIterFunc","none").set("paramC",0.0).set("paramCMod",0.0).set("paramCModType","none").set("paramCIter",0.0).set("paramCIterFunc","none").set("paramD",0.0).set("paramDMod",0.0).set("paramDModType","none").set("paramDIter",0.0).set("paramDIterFunc","none").set("paramE",0.0).set("paramEMod",0.0).set("paramEModType","none").set("paramEIter",0.0).set("paramEIterFunc","none").set("modDelay",0).set("i",3);
objects.add("Box_fleet_shields_nofill_accentbstroke_83YFUxXnhc", "Box").set("x",-17604).set("xMod",0.0).set("xModType","none").set("xIter",-6366.0).set("xIterFunc","none").set("xr",-4).set("xrMod",0.0).set("xrModType","none").set("xrIter",0.0).set("xrIterFunc","none").set("y",-29279).set("yMod",0.0).set("yModType","none").set("yIter",1785.0).set("yIterFunc","none").set("yr",14).set("yrMod",0.0).set("yrModType","none").set("yrIter",0.0).set("yrIterFunc","none").set("z",-90000).set("zMod",0.0).set("zModType","none").set("zIter",-3618.0).set("zIterFunc","none").set("zr",0).set("zrMod",0.0).set("zrModType","none").set("zrIter",0.0).set("zrIterFunc","none").set("w",17523.0).set("wMod",0.0).set("wModType","none").set("wIter",-4010.0).set("wIterFunc","none").set("h",1785.0).set("hMod",0.0).set("hModType","none").set("hIter",-10.0).set("hIterFunc","none").set("l",5100.0).set("lMod",0.0).set("lModType","none").set("lIter",-10.0).set("lIterFunc","none").set("s",100.0).set("sMod",0.0).set("sModType","none").set("sIter",0.0).set("sIterFunc","none").set("strokeColor",-4597324).set("strokeColorMod",0.0).set("strokeColorModType","none").set("strokeColorIter",0.0).set("strokeColorIterFunc","none").set("strokeWeight",2.0).set("strokeWeightMod",0.0).set("strokeWeightModType","none").set("strokeWeightIter",0.0).set("strokeWeightIterFunc","none").set("fillColor",0).set("fillColorMod",0.0).set("fillColorModType","none").set("fillColorIter",0.0).set("fillColorIterFunc","none").set("paramA",0.0).set("paramAMod",0.0).set("paramAModType","none").set("paramAIter",0.0).set("paramAIterFunc","none").set("paramB",0.0).set("paramBMod",0.0).set("paramBModType","none").set("paramBIter",0.0).set("paramBIterFunc","none").set("paramC",0.0).set("paramCMod",0.0).set("paramCModType","none").set("paramCIter",0.0).set("paramCIterFunc","none").set("paramD",0.0).set("paramDMod",0.0).set("paramDModType","none").set("paramDIter",0.0).set("paramDIterFunc","none").set("paramE",0.0).set("paramEMod",0.0).set("paramEModType","none").set("paramEIter",0.0).set("paramEIterFunc","none").set("modDelay",0).set("i",3);
objects.add("CurvedLine_birds_accentastroke_xI-OC_aslq", "CurvedLine").set("x",241).set("xMod",0.0).set("xModType","none").set("xIter",-324.0).set("xIterFunc","random 100").set("xr",90).set("xrMod",0.0).set("xrModType","none").set("xrIter",0.0).set("xrIterFunc","none").set("y",-494).set("yMod",0.0).set("yModType","none").set("yIter",0.0).set("yIterFunc","none").set("yr",0).set("yrMod",0.0).set("yrModType","none").set("yrIter",0.0).set("yrIterFunc","none").set("z",-1695).set("zMod",0.0).set("zModType","none").set("zIter",-58.0).set("zIterFunc","none").set("zr",0).set("zrMod",0.0).set("zrModType","none").set("zrIter",0.0).set("zrIterFunc","none").set("w",30.0).set("wMod",0.0).set("wModType","none").set("wIter",0.0).set("wIterFunc","none").set("h",100.0).set("hMod",0.0).set("hModType","none").set("hIter",0.0).set("hIterFunc","none").set("l",0.0).set("lMod",0.0).set("lModType","none").set("lIter",0.0).set("lIterFunc","none").set("s",0.0).set("sMod",0.0).set("sModType","none").set("sIter",0.0).set("sIterFunc","none").set("strokeColor",-5221004).set("strokeColorMod",0.0).set("strokeColorModType","none").set("strokeColorIter",0.0).set("strokeColorIterFunc","none").set("strokeWeight",2.0).set("strokeWeightMod",0.0).set("strokeWeightModType","none").set("strokeWeightIter",0.0).set("strokeWeightIterFunc","none").set("fillColor",0).set("fillColorMod",0.0).set("fillColorModType","none").set("fillColorIter",0.0).set("fillColorIterFunc","none").set("paramA",0.0).set("paramAMod",0.0).set("paramAModType","none").set("paramAIter",0.0).set("paramAIterFunc","none").set("paramB",-15.0).set("paramBMod",0.0).set("paramBModType","none").set("paramBIter",0.0).set("paramBIterFunc","none").set("paramC",0.0).set("paramCMod",0.0).set("paramCModType","none").set("paramCIter",0.0).set("paramCIterFunc","none").set("paramD",50.0).set("paramDMod",0.0).set("paramDModType","none").set("paramDIter",0.0).set("paramDIterFunc","none").set("paramE",0.0).set("paramEMod",0.0).set("paramEModType","none").set("paramEIter",0.0).set("paramEIterFunc","none").set("modDelay",0).set("i",31);
objects.add("Flatbox_city_flair_accentcstroke_accentbfill_ft6Iq-zQ_A", "Flatbox").set("x",-11480).set("xMod",0.0).set("xModType","none").set("xIter",12600.0).set("xIterFunc","sin(x)").set("xr",90).set("xrMod",0.0).set("xrModType","none").set("xrIter",0.0).set("xrIterFunc","none").set("y",-4850).set("yMod",0.0).set("yModType","none").set("yIter",400.0).set("yIterFunc","random 100").set("yr",0).set("yrMod",0.0).set("yrModType","none").set("yrIter",0.0).set("yrIterFunc","none").set("z",-46000).set("zMod",0.0).set("zModType","none").set("zIter",548.0).set("zIterFunc","none").set("zr",45).set("zrMod",0.0).set("zrModType","none").set("zrIter",10.0).set("zrIterFunc","none").set("w",465.0).set("wMod",0.0).set("wModType","none").set("wIter",0.0).set("wIterFunc","none").set("h",600.0).set("hMod",0.0).set("hModType","none").set("hIter",0.0).set("hIterFunc","none").set("l",7282.0).set("lMod",0.0).set("lModType","none").set("lIter",-800.0).set("lIterFunc","random 100").set("s",100.0).set("sMod",0.0).set("sModType","none").set("sIter",0.0).set("sIterFunc","none").set("strokeColor",-1005167).set("strokeColorMod",0.0).set("strokeColorModType","none").set("strokeColorIter",0.0).set("strokeColorIterFunc","none").set("strokeWeight",2.0).set("strokeWeightMod",0.0).set("strokeWeightModType","none").set("strokeWeightIter",0.0).set("strokeWeightIterFunc","none").set("fillColor",-4597324).set("fillColorMod",0.0).set("fillColorModType","none").set("fillColorIter",0.0).set("fillColorIterFunc","none").set("paramA",0.0).set("paramAMod",0.0).set("paramAModType","none").set("paramAIter",0.0).set("paramAIterFunc","none").set("paramB",0.0).set("paramBMod",0.0).set("paramBModType","none").set("paramBIter",0.0).set("paramBIterFunc","none").set("paramC",0.0).set("paramCMod",0.0).set("paramCModType","none").set("paramCIter",0.0).set("paramCIterFunc","none").set("paramD",0.0).set("paramDMod",0.0).set("paramDModType","none").set("paramDIter",0.0).set("paramDIterFunc","none").set("paramE",0.0).set("paramEMod",0.0).set("paramEModType","none").set("paramEIter",0.0).set("paramEIterFunc","none").set("modDelay",0).set("i",46);
objects.add("Flatbox_basepole_accentafill_accentbstroke_zw0Seer3-7", "Flatbox").set("x",403).set("xMod",0.0).set("xModType","none").set("xIter",20.0).set("xIterFunc","none").set("xr",90).set("xrMod",0.0).set("xrModType","none").set("xrIter",0.0).set("xrIterFunc","none").set("y",200).set("yMod",0.0).set("yModType","none").set("yIter",0.0).set("yIterFunc","none").set("yr",0).set("yrMod",0.0).set("yrModType","none").set("yrIter",0.0).set("yrIterFunc","none").set("z",345).set("zMod",0.0).set("zModType","none").set("zIter",-566.0).set("zIterFunc","none").set("zr",0).set("zrMod",0.0).set("zrModType","none").set("zrIter",65.0).set("zrIterFunc","random 100").set("w",-50.0).set("wMod",0.0).set("wModType","none").set("wIter",0.0).set("wIterFunc","none").set("h",60.0).set("hMod",0.0).set("hModType","none").set("hIter",0.0).set("hIterFunc","none").set("l",1110.0).set("lMod",0.0).set("lModType","none").set("lIter",0.0).set("lIterFunc","none").set("s",100.0).set("sMod",0.0).set("sModType","none").set("sIter",0.0).set("sIterFunc","none").set("strokeColor",-4597324).set("strokeColorMod",0.0).set("strokeColorModType","none").set("strokeColorIter",0.0).set("strokeColorIterFunc","none").set("strokeWeight",2.0).set("strokeWeightMod",0.0).set("strokeWeightModType","none").set("strokeWeightIter",0.0).set("strokeWeightIterFunc","none").set("fillColor",-5221004).set("fillColorMod",0.0).set("fillColorModType","none").set("fillColorIter",0.0).set("fillColorIterFunc","none").set("paramA",0.0).set("paramAMod",0.0).set("paramAModType","none").set("paramAIter",0.0).set("paramAIterFunc","none").set("paramB",0.0).set("paramBMod",0.0).set("paramBModType","none").set("paramBIter",0.0).set("paramBIterFunc","none").set("paramC",0.0).set("paramCMod",0.0).set("paramCModType","none").set("paramCIter",0.0).set("paramCIterFunc","none").set("paramD",0.0).set("paramDMod",0.0).set("paramDModType","none").set("paramDIter",0.0).set("paramDIterFunc","none").set("paramE",0.0).set("paramEMod",0.0).set("paramEModType","none").set("paramEIter",0.0).set("paramEIterFunc","none").set("modDelay",0).set("i",75);
objects.add("Rectangle_floor_accentcfill_YeU-eQkImS", "Rectangle").set("x",0).set("xMod",0.0).set("xModType","none").set("xIter",0.0).set("xIterFunc","none").set("xr",90).set("xrMod",0.0).set("xrModType","none").set("xrIter",0.0).set("xrIterFunc","none").set("y",356).set("yMod",0.0).set("yModType","none").set("yIter",0.0).set("yIterFunc","none").set("yr",0).set("yrMod",0.0).set("yrModType","none").set("yrIter",0.0).set("yrIterFunc","none").set("z",-20000).set("zMod",0.0).set("zModType","none").set("zIter",0.0).set("zIterFunc","none").set("zr",0).set("zrMod",0.0).set("zrModType","none").set("zrIter",0.0).set("zrIterFunc","none").set("w",100000.0).set("wMod",0.0).set("wModType","none").set("wIter",0.0).set("wIterFunc","none").set("h",60000.0).set("hMod",0.0).set("hModType","none").set("hIter",0.0).set("hIterFunc","none").set("l",0.0).set("lMod",0.0).set("lModType","none").set("lIter",0.0).set("lIterFunc","none").set("s",0.0).set("sMod",0.0).set("sModType","none").set("sIter",0.0).set("sIterFunc","none").set("strokeColor",-1005167).set("strokeColorMod",0.0).set("strokeColorModType","none").set("strokeColorIter",0.0).set("strokeColorIterFunc","none").set("strokeWeight",2.0).set("strokeWeightMod",0.0).set("strokeWeightModType","none").set("strokeWeightIter",0.0).set("strokeWeightIterFunc","none").set("fillColor",-1005167).set("fillColorMod",0.0).set("fillColorModType","none").set("fillColorIter",0.0).set("fillColorIterFunc","none").set("paramA",0.0).set("paramAMod",0.0).set("paramAModType","none").set("paramAIter",0.0).set("paramAIterFunc","none").set("paramB",0.0).set("paramBMod",0.0).set("paramBModType","none").set("paramBIter",0.0).set("paramBIterFunc","none").set("paramC",0.0).set("paramCMod",0.0).set("paramCModType","none").set("paramCIter",0.0).set("paramCIterFunc","none").set("paramD",0.0).set("paramDMod",0.0).set("paramDModType","none").set("paramDIter",0.0).set("paramDIterFunc","none").set("paramE",0.0).set("paramEMod",0.0).set("paramEModType","none").set("paramEIter",0.0).set("paramEIterFunc","none").set("modDelay",0).set("i",1);
objects.add("Triangle_leftvalley_accentbfill_bsOelKQfRJ", "Triangle").set("x",-93326).set("xMod",0.0).set("xModType","none").set("xIter",0.0).set("xIterFunc","none").set("xr",0).set("xrMod",0.0).set("xrModType","none").set("xrIter",0.0).set("xrIterFunc","none").set("y",0).set("yMod",0.0).set("yModType","none").set("yIter",0.0).set("yIterFunc","none").set("yr",0).set("yrMod",0.0).set("yrModType","none").set("yrIter",0.0).set("yrIterFunc","none").set("z",-72000).set("zMod",0.0).set("zModType","none").set("zIter",0.0).set("zIterFunc","none").set("zr",0).set("zrMod",0.0).set("zrModType","none").set("zrIter",0.0).set("zrIterFunc","none").set("w",301435.0).set("wMod",0.0).set("wModType","none").set("wIter",0.0).set("wIterFunc","none").set("h",118326.0).set("hMod",0.0).set("hModType","none").set("hIter",0.0).set("hIterFunc","none").set("l",0.0).set("lMod",0.0).set("lModType","none").set("lIter",0.0).set("lIterFunc","none").set("s",100.0).set("sMod",0.0).set("sModType","none").set("sIter",0.0).set("sIterFunc","none").set("strokeColor",-4597324).set("strokeColorMod",0.0).set("strokeColorModType","none").set("strokeColorIter",0.0).set("strokeColorIterFunc","none").set("strokeWeight",2.0).set("strokeWeightMod",0.0).set("strokeWeightModType","none").set("strokeWeightIter",0.0).set("strokeWeightIterFunc","none").set("fillColor",-4597324).set("fillColorMod",0.0).set("fillColorModType","none").set("fillColorIter",0.0).set("fillColorIterFunc","none").set("paramA",0.0).set("paramAMod",0.0).set("paramAModType","none").set("paramAIter",0.0).set("paramAIterFunc","none").set("paramB",0.0).set("paramBMod",0.0).set("paramBModType","none").set("paramBIter",0.0).set("paramBIterFunc","none").set("paramC",0.0).set("paramCMod",0.0).set("paramCModType","none").set("paramCIter",0.0).set("paramCIterFunc","none").set("paramD",0.0).set("paramDMod",0.0).set("paramDModType","none").set("paramDIter",0.0).set("paramDIterFunc","none").set("paramE",0.0).set("paramEMod",0.0).set("paramEModType","none").set("paramEIter",0.0).set("paramEIterFunc","none").set("variation","left-right").set("modDelay",0).set("i",1);
objects.add("background", "OavpObject").set("x",0).set("xMod",0.0).set("xModType","none").set("xIter",0.0).set("xIterFunc","none").set("xr",0).set("xrMod",0.0).set("xrModType","none").set("xrIter",0.0).set("xrIterFunc","none").set("y",0).set("yMod",0.0).set("yModType","none").set("yIter",0.0).set("yIterFunc","none").set("yr",0).set("yrMod",0.0).set("yrModType","none").set("yrIter",0.0).set("yrIterFunc","none").set("z",0).set("zMod",0.0).set("zModType","none").set("zIter",0.0).set("zIterFunc","none").set("zr",0).set("zrMod",0.0).set("zrModType","none").set("zrIter",0.0).set("zrIterFunc","none").set("w",100.0).set("wMod",0.0).set("wModType","none").set("wIter",0.0).set("wIterFunc","none").set("h",100.0).set("hMod",0.0).set("hModType","none").set("hIter",0.0).set("hIterFunc","none").set("l",0.0).set("lMod",0.0).set("lModType","none").set("lIter",0.0).set("lIterFunc","none").set("s",100.0).set("sMod",0.0).set("sModType","none").set("sIter",0.0).set("sIterFunc","none").set("strokeColor",-4597324).set("strokeColorMod",0.0).set("strokeColorModType","none").set("strokeColorIter",0.0).set("strokeColorIterFunc","none").set("strokeWeight",2.0).set("strokeWeightMod",0.0).set("strokeWeightModType","none").set("strokeWeightIter",0.0).set("strokeWeightIterFunc","none").set("fillColor",-3043697).set("fillColorMod",0.0).set("fillColorModType","none").set("fillColorIter",0.0).set("fillColorIterFunc","none").set("paramA",0.0).set("paramAMod",0.0).set("paramAModType","none").set("paramAIter",0.0).set("paramAIterFunc","none").set("paramB",0.0).set("paramBMod",0.0).set("paramBModType","none").set("paramBIter",0.0).set("paramBIterFunc","none").set("paramC",0.0).set("paramCMod",0.0).set("paramCModType","none").set("paramCIter",0.0).set("paramCIterFunc","none").set("paramD",0.0).set("paramDMod",0.0).set("paramDModType","none").set("paramDIter",0.0).set("paramDIterFunc","none").set("paramE",0.0).set("paramEMod",0.0).set("paramEModType","none").set("paramEIter",0.0).set("paramEIterFunc","none").set("modDelay",0).set("i",1);
objects.add("Rectangle_horizon_nostroke_accentafill_WP4VPGf2V", "Rectangle").set("x",0).set("xMod",0.0).set("xModType","none").set("xIter",0.0).set("xIterFunc","none").set("xr",0).set("xrMod",0.0).set("xrModType","none").set("xrIter",0.0).set("xrIterFunc","none").set("y",40000).set("yMod",0.0).set("yModType","none").set("yIter",0.0).set("yIterFunc","none").set("yr",0).set("yrMod",0.0).set("yrModType","none").set("yrIter",0.0).set("yrIterFunc","none").set("z",-65000).set("zMod",0.0).set("zModType","none").set("zIter",0.0).set("zIterFunc","none").set("zr",0).set("zrMod",0.0).set("zrModType","none").set("zrIter",0.0).set("zrIterFunc","none").set("w",200000.0).set("wMod",0.0).set("wModType","none").set("wIter",0.0).set("wIterFunc","none").set("h",80000.0).set("hMod",0.0).set("hModType","none").set("hIter",0.0).set("hIterFunc","none").set("l",0.0).set("lMod",0.0).set("lModType","none").set("lIter",0.0).set("lIterFunc","none").set("s",0.0).set("sMod",0.0).set("sModType","none").set("sIter",0.0).set("sIterFunc","none").set("strokeColor",0).set("strokeColorMod",0.0).set("strokeColorModType","none").set("strokeColorIter",0.0).set("strokeColorIterFunc","none").set("strokeWeight",2.0).set("strokeWeightMod",0.0).set("strokeWeightModType","none").set("strokeWeightIter",0.0).set("strokeWeightIterFunc","none").set("fillColor",-5221004).set("fillColorMod",0.0).set("fillColorModType","none").set("fillColorIter",0.0).set("fillColorIterFunc","none").set("paramA",0.0).set("paramAMod",0.0).set("paramAModType","none").set("paramAIter",0.0).set("paramAIterFunc","none").set("paramB",0.0).set("paramBMod",0.0).set("paramBModType","none").set("paramBIter",0.0).set("paramBIterFunc","none").set("paramC",0.0).set("paramCMod",0.0).set("paramCModType","none").set("paramCIter",0.0).set("paramCIterFunc","none").set("paramD",0.0).set("paramDMod",0.0).set("paramDModType","none").set("paramDIter",0.0).set("paramDIterFunc","none").set("paramE",0.0).set("paramEMod",0.0).set("paramEModType","none").set("paramEIter",0.0).set("paramEIterFunc","none").set("modDelay",0).set("i",1);
objects.add("Triangle_rightvalley_accentcfill_E4gdX6tK4Z", "Triangle").set("x",-50231).set("xMod",0.0).set("xModType","none").set("xIter",0.0).set("xIterFunc","none").set("xr",0).set("xrMod",0.0).set("xrModType","none").set("xrIter",0.0).set("xrIterFunc","none").set("y",0).set("yMod",0.0).set("yModType","none").set("yIter",0.0).set("yIterFunc","none").set("yr",0).set("yrMod",0.0).set("yrModType","none").set("yrIter",0.0).set("yrIterFunc","none").set("z",-70000).set("zMod",0.0).set("zModType","none").set("zIter",0.0).set("zIterFunc","none").set("zr",0).set("zrMod",0.0).set("zrModType","none").set("zrIter",0.0).set("zrIterFunc","none").set("w",-311452.0).set("wMod",0.0).set("wModType","none").set("wIter",0.0).set("wIterFunc","none").set("h",75231.0).set("hMod",0.0).set("hModType","none").set("hIter",0.0).set("hIterFunc","none").set("l",0.0).set("lMod",0.0).set("lModType","none").set("lIter",0.0).set("lIterFunc","none").set("s",100.0).set("sMod",0.0).set("sModType","none").set("sIter",0.0).set("sIterFunc","none").set("strokeColor",-3043697).set("strokeColorMod",0.0).set("strokeColorModType","none").set("strokeColorIter",0.0).set("strokeColorIterFunc","none").set("strokeWeight",2.0).set("strokeWeightMod",0.0).set("strokeWeightModType","none").set("strokeWeightIter",0.0).set("strokeWeightIterFunc","none").set("fillColor",-1005167).set("fillColorMod",0.0).set("fillColorModType","none").set("fillColorIter",0.0).set("fillColorIterFunc","none").set("paramA",0.0).set("paramAMod",0.0).set("paramAModType","none").set("paramAIter",0.0).set("paramAIterFunc","none").set("paramB",0.0).set("paramBMod",0.0).set("paramBModType","none").set("paramBIter",0.0).set("paramBIterFunc","none").set("paramC",0.0).set("paramCMod",0.0).set("paramCModType","none").set("paramCIter",0.0).set("paramCIterFunc","none").set("paramD",0.0).set("paramDMod",0.0).set("paramDModType","none").set("paramDIter",0.0).set("paramDIterFunc","none").set("paramE",0.0).set("paramEMod",0.0).set("paramEModType","none").set("paramEIter",0.0).set("paramEIterFunc","none").set("variation","left-right").set("modDelay",0).set("i",1);
objects.add("Box_fleet_main_accentafill_backgroundstroke_TLbYfE-aZj", "Box").set("x",-17404).set("xMod",0.0).set("xModType","none").set("xIter",-6366.0).set("xIterFunc","none").set("xr",-4).set("xrMod",0.0).set("xrModType","none").set("xrIter",0.0).set("xrIterFunc","none").set("y",-29879).set("yMod",0.0).set("yModType","none").set("yIter",1785.0).set("yIterFunc","none").set("yr",14).set("yrMod",0.0).set("yrModType","none").set("yrIter",0.0).set("yrIterFunc","none").set("z",-90000).set("zMod",0.0).set("zModType","none").set("zIter",-3618.0).set("zIterFunc","none").set("zr",0).set("zrMod",0.0).set("zrModType","none").set("zrIter",0.0).set("zrIterFunc","none").set("w",17523.0).set("wMod",0.0).set("wModType","none").set("wIter",-4010.0).set("wIterFunc","none").set("h",1785.0).set("hMod",0.0).set("hModType","none").set("hIter",-10.0).set("hIterFunc","none").set("l",5100.0).set("lMod",0.0).set("lModType","none").set("lIter",-10.0).set("lIterFunc","none").set("s",100.0).set("sMod",0.0).set("sModType","none").set("sIter",0.0).set("sIterFunc","none").set("strokeColor",-3043697).set("strokeColorMod",0.0).set("strokeColorModType","none").set("strokeColorIter",0.0).set("strokeColorIterFunc","none").set("strokeWeight",2.0).set("strokeWeightMod",0.0).set("strokeWeightModType","none").set("strokeWeightIter",0.0).set("strokeWeightIterFunc","none").set("fillColor",-5221004).set("fillColorMod",0.0).set("fillColorModType","none").set("fillColorIter",0.0).set("fillColorIterFunc","none").set("paramA",0.0).set("paramAMod",0.0).set("paramAModType","none").set("paramAIter",0.0).set("paramAIterFunc","none").set("paramB",0.0).set("paramBMod",0.0).set("paramBModType","none").set("paramBIter",0.0).set("paramBIterFunc","none").set("paramC",0.0).set("paramCMod",0.0).set("paramCModType","none").set("paramCIter",0.0).set("paramCIterFunc","none").set("paramD",0.0).set("paramDMod",0.0).set("paramDModType","none").set("paramDIter",0.0).set("paramDIterFunc","none").set("paramE",0.0).set("paramEMod",0.0).set("paramEModType","none").set("paramEIter",0.0).set("paramEIterFunc","none").set("modDelay",0).set("i",3);
objects.add("camera", "OavpObject").set("x",0).set("xMod",0.0).set("xModType","none").set("xIter",0.0).set("xIterFunc","none").set("xr",0).set("xrMod",0.0).set("xrModType","none").set("xrIter",0.0).set("xrIterFunc","none").set("y",0).set("yMod",0.0).set("yModType","none").set("yIter",0.0).set("yIterFunc","none").set("yr",0).set("yrMod",0.0).set("yrModType","none").set("yrIter",0.0).set("yrIterFunc","none").set("z",0).set("zMod",0.0).set("zModType","none").set("zIter",0.0).set("zIterFunc","none").set("zr",0).set("zrMod",0.0).set("zrModType","none").set("zrIter",0.0).set("zrIterFunc","none").set("w",0.0).set("wMod",0.0).set("wModType","none").set("wIter",0.0).set("wIterFunc","none").set("h",0.0).set("hMod",0.0).set("hModType","none").set("hIter",0.0).set("hIterFunc","none").set("l",0.0).set("lMod",0.0).set("lModType","none").set("lIter",0.0).set("lIterFunc","none").set("s",100.0).set("sMod",0.0).set("sModType","none").set("sIter",0.0).set("sIterFunc","none").set("strokeColor",-3043697).set("strokeColorMod",0.0).set("strokeColorModType","none").set("strokeColorIter",0.0).set("strokeColorIterFunc","none").set("strokeWeight",2.0).set("strokeWeightMod",0.0).set("strokeWeightModType","none").set("strokeWeightIter",0.0).set("strokeWeightIterFunc","none").set("fillColor",-5221004).set("fillColorMod",0.0).set("fillColorModType","none").set("fillColorIter",0.0).set("fillColorIterFunc","none").set("paramA",100000.0).set("paramAMod",0.0).set("paramAModType","none").set("paramAIter",0.0).set("paramAIterFunc","none").set("paramB",0.0).set("paramBMod",0.0).set("paramBModType","none").set("paramBIter",0.0).set("paramBIterFunc","none").set("paramC",0.0).set("paramCMod",0.0).set("paramCModType","none").set("paramCIter",0.0).set("paramCIterFunc","none").set("paramD",0.0).set("paramDMod",0.0).set("paramDModType","none").set("paramDIter",0.0).set("paramDIterFunc","none").set("paramE",0.0).set("paramEMod",0.0).set("paramEModType","none").set("paramEIter",0.0).set("paramEIterFunc","none").set("modDelay",0).set("i",1);
objects.add("Flatbox_poletip_accentbfill_accentastroke_AnKoh3giJn", "Flatbox").set("x",403).set("xMod",0.0).set("xModType","none").set("xIter",20.0).set("xIterFunc","none").set("xr",90).set("xrMod",0.0).set("xrModType","none").set("xrIter",0.0).set("xrIterFunc","none").set("y",-415).set("yMod",0.0).set("yModType","none").set("yIter",0.0).set("yIterFunc","none").set("yr",0).set("yrMod",0.0).set("yrModType","none").set("yrIter",0.0).set("yrIterFunc","none").set("z",345).set("zMod",0.0).set("zModType","none").set("zIter",-566.0).set("zIterFunc","none").set("zr",0).set("zrMod",0.0).set("zrModType","none").set("zrIter",65.0).set("zrIterFunc","random 100").set("w",-50.0).set("wMod",0.0).set("wModType","none").set("wIter",0.0).set("wIterFunc","none").set("h",106.0).set("hMod",0.0).set("hModType","none").set("hIter",0.0).set("hIterFunc","none").set("l",110.0).set("lMod",0.0).set("lModType","none").set("lIter",0.0).set("lIterFunc","none").set("s",100.0).set("sMod",0.0).set("sModType","none").set("sIter",0.0).set("sIterFunc","none").set("strokeColor",-5221004).set("strokeColorMod",0.0).set("strokeColorModType","none").set("strokeColorIter",0.0).set("strokeColorIterFunc","none").set("strokeWeight",2.0).set("strokeWeightMod",0.0).set("strokeWeightModType","none").set("strokeWeightIter",0.0).set("strokeWeightIterFunc","none").set("fillColor",-4597324).set("fillColorMod",0.0).set("fillColorModType","none").set("fillColorIter",0.0).set("fillColorIterFunc","none").set("paramA",0.0).set("paramAMod",0.0).set("paramAModType","none").set("paramAIter",0.0).set("paramAIterFunc","none").set("paramB",0.0).set("paramBMod",0.0).set("paramBModType","none").set("paramBIter",0.0).set("paramBIterFunc","none").set("paramC",0.0).set("paramCMod",0.0).set("paramCModType","none").set("paramCIter",0.0).set("paramCIterFunc","none").set("paramD",0.0).set("paramDMod",0.0).set("paramDModType","none").set("paramDIter",0.0).set("paramDIterFunc","none").set("paramE",0.0).set("paramEMod",0.0).set("paramEModType","none").set("paramEIter",0.0).set("paramEIterFunc","none").set("modDelay",0).set("i",75);
}
void setupSketchPostEditor() {
editor.setPaletteByArrayString("#288D85,#B9D9B4,#D18E8F,#B05574,#F0A991");
editor.setBackgroundColor(-3043697);
editor.setAccentA(-5221004);
editor.setAccentB(-4597324);
editor.setAccentC(-1005167);
editor.setAccentD(-14119547);
}
void updateSketch() {}
void drawSketch() {}
`

export const EXAMPLE_SKETCH_DATA_OBJECT = {
  "name": "Example Sketch Name",
  "date": "Sat Jan 20 00:17:17 EST 2024",
  "seed": 95,
  "colors": {
    "background": {
      "value": "#D18E8F",
      "int": -3043697,
      "name": "red"
    },
    "accentA": {
      "value": "#B05574",
      "int": -5221004,
      "name": "red"
    },
    "accentB": {
      "value": "#B9D9B4",
      "int": -4597324,
      "name": "red"
    },
    "accentC": {
      "value": "#F0A991",
      "int": -1005167,
      "name": "red"
    },
    "accentD": {
      "value": "#288D85",
      "int": -14119547,
      "name": "red"
    }
  },
  "tags": [
    "basepole",
    "birds",
    "city",
    "flair",
    "fleet",
    "floor",
    "horizon",
    "leftvalley",
    "lights",
    "poletip",
    "rightvalley",
    "shields"
  ],
  "id": "00001",
  "objects": [
    {
      "name": "Flatbox_city_main_accentastroke_accentbfill_RBui0TpNN0",
      "shape": "Flatbox",
      "properties": [
        { "property": "x", "value": -11480 },
        { "property": "xMod", "value": 0.0 },
        { "property": "xModType", "value": "none" },
        { "property": "xIter", "value": 12600.0 },
        { "property": "xIterFunc", "value": "sin(x)" },
        { "property": "xr", "value": 90 },
        { "property": "xrMod", "value": 0.0 },
        { "property": "xrModType", "value": "none" },
        { "property": "xrIter", "value": 0.0 },
        { "property": "xrIterFunc", "value": "none" },
        { "property": "y", "value": -4450 },
        { "property": "yMod", "value": 0.0 },
        { "property": "yModType", "value": "none" },
        { "property": "yIter", "value": 400.0 },
        { "property": "yIterFunc", "value": "random 100" },
        { "property": "yr", "value": 0 },
        { "property": "yrMod", "value": 0.0 },
        { "property": "yrModType", "value": "none" },
        { "property": "yrIter", "value": 0.0 },
        { "property": "yrIterFunc", "value": "none" },
        { "property": "z", "value": -46000 },
        { "property": "zMod", "value": 0.0 },
        { "property": "zModType", "value": "none" },
        { "property": "zIter", "value": 548.0 },
        { "property": "zIterFunc", "value": "none" },
        { "property": "zr", "value": 45 },
        { "property": "zrMod", "value": 0.0 },
        { "property": "zrModType", "value": "none" },
        { "property": "zrIter", "value": 10.0 },
        { "property": "zrIterFunc", "value": "none" },
        { "property": "w", "value": 798.0 },
        { "property": "wMod", "value": 0.0 },
        { "property": "wModType", "value": "none" },
        { "property": "wIter", "value": 0.0 },
        { "property": "wIterFunc", "value": "none" },
        { "property": "h", "value": 600.0 },
        { "property": "hMod", "value": 0.0 },
        { "property": "hModType", "value": "none" },
        { "property": "hIter", "value": 0.0 },
        { "property": "hIterFunc", "value": "none" },
        { "property": "l", "value": 10000.0 },
        { "property": "lMod", "value": 0.0 },
        { "property": "lModType", "value": "none" },
        { "property": "lIter", "value": -800.0 },
        { "property": "lIterFunc", "value": "random 100" },
        { "property": "s", "value": 100.0 },
        { "property": "sMod", "value": 0.0 },
        { "property": "sModType", "value": "none" },
        { "property": "sIter", "value": 0.0 },
        { "property": "sIterFunc", "value": "none" },
        { "property": "strokeColor", "value": -5221004 },
        { "property": "strokeColorMod", "value": 0.0 },
        { "property": "strokeColorModType", "value": "none" },
        { "property": "strokeColorIter", "value": 0.0 },
        { "property": "strokeColorIterFunc", "value": "none" },
        { "property": "strokeWeight", "value": 2.0 },
        { "property": "strokeWeightMod", "value": 0.0 },
        { "property": "strokeWeightModType", "value": "none" },
        { "property": "strokeWeightIter", "value": 0.0 },
        { "property": "strokeWeightIterFunc", "value": "none" },
        { "property": "fillColor", "value": -4597324 },
        { "property": "fillColorMod", "value": 0.0 },
        { "property": "fillColorModType", "value": "none" },
        { "property": "fillColorIter", "value": 0.0 },
        { "property": "fillColorIterFunc", "value": "none" },
        { "property": "paramA", "value": 0.0 },
        { "property": "paramAMod", "value": 0.0 },
        { "property": "paramAModType", "value": "none" },
        { "property": "paramAIter", "value": 0.0 },
        { "property": "paramAIterFunc", "value": "none" },
        { "property": "paramB", "value": 0.0 },
        { "property": "paramBMod", "value": 0.0 },
        { "property": "paramBModType", "value": "none" },
        { "property": "paramBIter", "value": 0.0 },
        { "property": "paramBIterFunc", "value": "none" },
        { "property": "paramC", "value": 0.0 },
        { "property": "paramCMod", "value": 0.0 },
        { "property": "paramCModType", "value": "none" },
        { "property": "paramCIter", "value": 0.0 },
        { "property": "paramCIterFunc", "value": "none" },
        { "property": "paramD", "value": 0.0 },
        { "property": "paramDMod", "value": 0.0 },
        { "property": "paramDModType", "value": "none" },
        { "property": "paramDIter", "value": 0.0 },
        { "property": "paramDIterFunc", "value": "none" },
        { "property": "paramE", "value": 0.0 },
        { "property": "paramEMod", "value": 0.0 },
        { "property": "paramEModType", "value": "none" },
        { "property": "paramEIter", "value": 0.0 },
        { "property": "paramEIterFunc", "value": "none" },
        { "property": "modDelay", "value": 0 },
        { "property": "i", "value": 46 }
      ]
    },
    {
      "name": "Rectangle_fleet_lights_nostroke_accentcfill_4yYfI00iNI",
      "shape": "Rectangle",
      "properties": [
        { "property": "x", "value": -15804 },
        { "property": "xMod", "value": 0.0 },
        { "property": "xModType", "value": "none" },
        { "property": "xIter", "value": -6366.0 },
        { "property": "xIterFunc", "value": "none" },
        { "property": "xr", "value": -4 },
        { "property": "xrMod", "value": 0.0 },
        { "property": "xrModType", "value": "none" },
        { "property": "xrIter", "value": 0.0 },
        { "property": "xrIterFunc", "value": "none" },
        { "property": "y", "value": -26879 },
        { "property": "yMod", "value": 0.0 },
        { "property": "yModType", "value": "none" },
        { "property": "yIter", "value": 1785.0 },
        { "property": "yIterFunc", "value": "none" },
        { "property": "yr", "value": 14 },
        { "property": "yrMod", "value": 0.0 },
        { "property": "yrModType", "value": "none" },
        { "property": "yrIter", "value": 0.0 },
        { "property": "yrIterFunc", "value": "none" },
        { "property": "z", "value": -86000 },
        { "property": "zMod", "value": 0.0 },
        { "property": "zModType", "value": "none" },
        { "property": "zIter", "value": -3618.0 },
        { "property": "zIterFunc", "value": "none" },
        { "property": "zr", "value": 0 },
        { "property": "zrMod", "value": 0.0 },
        { "property": "zrModType", "value": "none" },
        { "property": "zrIter", "value": 0.0 },
        { "property": "zrIterFunc", "value": "none" },
        { "property": "w", "value": 8761.5 },
        { "property": "wMod", "value": 0.0 },
        { "property": "wModType", "value": "none" },
        { "property": "wIter", "value": -4010.0 },
        { "property": "wIterFunc", "value": "none" },
        { "property": "h", "value": 500.0 },
        { "property": "hMod", "value": 0.0 },
        { "property": "hModType", "value": "none" },
        { "property": "hIter", "value": -10.0 },
        { "property": "hIterFunc", "value": "none" },
        { "property": "l", "value": 5100.0 },
        { "property": "lMod", "value": 0.0 },
        { "property": "lModType", "value": "none" },
        { "property": "lIter", "value": -10.0 },
        { "property": "lIterFunc", "value": "none" },
        { "property": "s", "value": 100.0 },
        { "property": "sMod", "value": 0.0 },
        { "property": "sModType", "value": "none" },
        { "property": "sIter", "value": 0.0 },
        { "property": "sIterFunc", "value": "none" },
        { "property": "strokeColor", "value": 0 },
        { "property": "strokeColorMod", "value": 0.0 },
        { "property": "strokeColorModType", "value": "none" },
        { "property": "strokeColorIter", "value": 0.0 },
        { "property": "strokeColorIterFunc", "value": "none" },
        { "property": "strokeWeight", "value": 2.0 },
        { "property": "strokeWeightMod", "value": 0.0 },
        { "property": "strokeWeightModType", "value": "none" },
        { "property": "strokeWeightIter", "value": 0.0 },
        { "property": "strokeWeightIterFunc", "value": "none" },
        { "property": "fillColor", "value": -1005167 },
        { "property": "fillColorMod", "value": 0.0 },
        { "property": "fillColorModType", "value": "none" },
        { "property": "fillColorIter", "value": 0.0 },
        { "property": "fillColorIterFunc", "value": "none" },
        { "property": "paramA", "value": 0.0 },
        { "property": "paramAMod", "value": 0.0 },
        { "property": "paramAModType", "value": "none" },
        { "property": "paramAIter", "value": 0.0 },
        { "property": "paramAIterFunc", "value": "none" },
        { "property": "paramB", "value": 0.0 },
        { "property": "paramBMod", "value": 0.0 },
        { "property": "paramBModType", "value": "none" },
        { "property": "paramBIter", "value": 0.0 },
        { "property": "paramBIterFunc", "value": "none" },
        { "property": "paramC", "value": 0.0 },
        { "property": "paramCMod", "value": 0.0 },
        { "property": "paramCModType", "value": "none" },
        { "property": "paramCIter", "value": 0.0 },
        { "property": "paramCIterFunc", "value": "none" },
        { "property": "paramD", "value": 0.0 },
        { "property": "paramDMod", "value": 0.0 },
        { "property": "paramDModType", "value": "none" },
        { "property": "paramDIter", "value": 0.0 },
        { "property": "paramDIterFunc", "value": "none" },
        { "property": "paramE", "value": 0.0 },
        { "property": "paramEMod", "value": 0.0 },
        { "property": "paramEModType", "value": "none" },
        { "property": "paramEIter", "value": 0.0 },
        { "property": "paramEIterFunc", "value": "none" },
        { "property": "modDelay", "value": 0 },
        { "property": "i", "value": 3 }
      ]
    },
    {
      "name": "Box_fleet_shields_nofill_accentbstroke_83YFUxXnhc",
      "shape": "Box",
      "properties": [
        { "property": "x", "value": -17604 },
        { "property": "xMod", "value": 0.0 },
        { "property": "xModType", "value": "none" },
        { "property": "xIter", "value": -6366.0 },
        { "property": "xIterFunc", "value": "none" },
        { "property": "xr", "value": -4 },
        { "property": "xrMod", "value": 0.0 },
        { "property": "xrModType", "value": "none" },
        { "property": "xrIter", "value": 0.0 },
        { "property": "xrIterFunc", "value": "none" },
        { "property": "y", "value": -29279 },
        { "property": "yMod", "value": 0.0 },
        { "property": "yModType", "value": "none" },
        { "property": "yIter", "value": 1785.0 },
        { "property": "yIterFunc", "value": "none" },
        { "property": "yr", "value": 14 },
        { "property": "yrMod", "value": 0.0 },
        { "property": "yrModType", "value": "none" },
        { "property": "yrIter", "value": 0.0 },
        { "property": "yrIterFunc", "value": "none" },
        { "property": "z", "value": -90000 },
        { "property": "zMod", "value": 0.0 },
        { "property": "zModType", "value": "none" },
        { "property": "zIter", "value": -3618.0 },
        { "property": "zIterFunc", "value": "none" },
        { "property": "zr", "value": 0 },
        { "property": "zrMod", "value": 0.0 },
        { "property": "zrModType", "value": "none" },
        { "property": "zrIter", "value": 0.0 },
        { "property": "zrIterFunc", "value": "none" },
        { "property": "w", "value": 17523.0 },
        { "property": "wMod", "value": 0.0 },
        { "property": "wModType", "value": "none" },
        { "property": "wIter", "value": -4010.0 },
        { "property": "wIterFunc", "value": "none" },
        { "property": "h", "value": 1785.0 },
        { "property": "hMod", "value": 0.0 },
        { "property": "hModType", "value": "none" },
        { "property": "hIter", "value": -10.0 },
        { "property": "hIterFunc", "value": "none" },
        { "property": "l", "value": 5100.0 },
        { "property": "lMod", "value": 0.0 },
        { "property": "lModType", "value": "none" },
        { "property": "lIter", "value": -10.0 },
        { "property": "lIterFunc", "value": "none" },
        { "property": "s", "value": 100.0 },
        { "property": "sMod", "value": 0.0 },
        { "property": "sModType", "value": "none" },
        { "property": "sIter", "value": 0.0 },
        { "property": "sIterFunc", "value": "none" },
        { "property": "strokeColor", "value": -4597324 },
        { "property": "strokeColorMod", "value": 0.0 },
        { "property": "strokeColorModType", "value": "none" },
        { "property": "strokeColorIter", "value": 0.0 },
        { "property": "strokeColorIterFunc", "value": "none" },
        { "property": "strokeWeight", "value": 2.0 },
        { "property": "strokeWeightMod", "value": 0.0 },
        { "property": "strokeWeightModType", "value": "none" },
        { "property": "strokeWeightIter", "value": 0.0 },
        { "property": "strokeWeightIterFunc", "value": "none" },
        { "property": "fillColor", "value": 0 },
        { "property": "fillColorMod", "value": 0.0 },
        { "property": "fillColorModType", "value": "none" },
        { "property": "fillColorIter", "value": 0.0 },
        { "property": "fillColorIterFunc", "value": "none" },
        { "property": "paramA", "value": 0.0 },
        { "property": "paramAMod", "value": 0.0 },
        { "property": "paramAModType", "value": "none" },
        { "property": "paramAIter", "value": 0.0 },
        { "property": "paramAIterFunc", "value": "none" },
        { "property": "paramB", "value": 0.0 },
        { "property": "paramBMod", "value": 0.0 },
        { "property": "paramBModType", "value": "none" },
        { "property": "paramBIter", "value": 0.0 },
        { "property": "paramBIterFunc", "value": "none" },
        { "property": "paramC", "value": 0.0 },
        { "property": "paramCMod", "value": 0.0 },
        { "property": "paramCModType", "value": "none" },
        { "property": "paramCIter", "value": 0.0 },
        { "property": "paramCIterFunc", "value": "none" },
        { "property": "paramD", "value": 0.0 },
        { "property": "paramDMod", "value": 0.0 },
        { "property": "paramDModType", "value": "none" },
        { "property": "paramDIter", "value": 0.0 },
        { "property": "paramDIterFunc", "value": "none" },
        { "property": "paramE", "value": 0.0 },
        { "property": "paramEMod", "value": 0.0 },
        { "property": "paramEModType", "value": "none" },
        { "property": "paramEIter", "value": 0.0 },
        { "property": "paramEIterFunc", "value": "none" },
        { "property": "modDelay", "value": 0 },
        { "property": "i", "value": 3 }
      ]
    },
    {
      "name": "CurvedLine_birds_accentastroke_xI-OC_aslq",
      "shape": "CurvedLine",
      "properties": [
        { "property": "x", "value": 241 },
        { "property": "xMod", "value": 0.0 },
        { "property": "xModType", "value": "none" },
        { "property": "xIter", "value": -324.0 },
        { "property": "xIterFunc", "value": "random 100" },
        { "property": "xr", "value": 90 },
        { "property": "xrMod", "value": 0.0 },
        { "property": "xrModType", "value": "none" },
        { "property": "xrIter", "value": 0.0 },
        { "property": "xrIterFunc", "value": "none" },
        { "property": "y", "value": -494 },
        { "property": "yMod", "value": 0.0 },
        { "property": "yModType", "value": "none" },
        { "property": "yIter", "value": 0.0 },
        { "property": "yIterFunc", "value": "none" },
        { "property": "yr", "value": 0 },
        { "property": "yrMod", "value": 0.0 },
        { "property": "yrModType", "value": "none" },
        { "property": "yrIter", "value": 0.0 },
        { "property": "yrIterFunc", "value": "none" },
        { "property": "z", "value": -1695 },
        { "property": "zMod", "value": 0.0 },
        { "property": "zModType", "value": "none" },
        { "property": "zIter", "value": -58.0 },
        { "property": "zIterFunc", "value": "none" },
        { "property": "zr", "value": 0 },
        { "property": "zrMod", "value": 0.0 },
        { "property": "zrModType", "value": "none" },
        { "property": "zrIter", "value": 0.0 },
        { "property": "zrIterFunc", "value": "none" },
        { "property": "w", "value": 30.0 },
        { "property": "wMod", "value": 0.0 },
        { "property": "wModType", "value": "none" },
        { "property": "wIter", "value": 0.0 },
        { "property": "wIterFunc", "value": "none" },
        { "property": "h", "value": 100.0 },
        { "property": "hMod", "value": 0.0 },
        { "property": "hModType", "value": "none" },
        { "property": "hIter", "value": 0.0 },
        { "property": "hIterFunc", "value": "none" },
        { "property": "l", "value": 0.0 },
        { "property": "lMod", "value": 0.0 },
        { "property": "lModType", "value": "none" },
        { "property": "lIter", "value": 0.0 },
        { "property": "lIterFunc", "value": "none" },
        { "property": "s", "value": 0.0 },
        { "property": "sMod", "value": 0.0 },
        { "property": "sModType", "value": "none" },
        { "property": "sIter", "value": 0.0 },
        { "property": "sIterFunc", "value": "none" },
        { "property": "strokeColor", "value": -5221004 },
        { "property": "strokeColorMod", "value": 0.0 },
        { "property": "strokeColorModType", "value": "none" },
        { "property": "strokeColorIter", "value": 0.0 },
        { "property": "strokeColorIterFunc", "value": "none" },
        { "property": "strokeWeight", "value": 2.0 },
        { "property": "strokeWeightMod", "value": 0.0 },
        { "property": "strokeWeightModType", "value": "none" },
        { "property": "strokeWeightIter", "value": 0.0 },
        { "property": "strokeWeightIterFunc", "value": "none" },
        { "property": "fillColor", "value": 0 },
        { "property": "fillColorMod", "value": 0.0 },
        { "property": "fillColorModType", "value": "none" },
        { "property": "fillColorIter", "value": 0.0 },
        { "property": "fillColorIterFunc", "value": "none" },
        { "property": "paramA", "value": 0.0 },
        { "property": "paramAMod", "value": 0.0 },
        { "property": "paramAModType", "value": "none" },
        { "property": "paramAIter", "value": 0.0 },
        { "property": "paramAIterFunc", "value": "none" },
        { "property": "paramB", "value": -15.0 },
        { "property": "paramBMod", "value": 0.0 },
        { "property": "paramBModType", "value": "none" },
        { "property": "paramBIter", "value": 0.0 },
        { "property": "paramBIterFunc", "value": "none" },
        { "property": "paramC", "value": 0.0 },
        { "property": "paramCMod", "value": 0.0 },
        { "property": "paramCModType", "value": "none" },
        { "property": "paramCIter", "value": 0.0 },
        { "property": "paramCIterFunc", "value": "none" },
        { "property": "paramD", "value": 50.0 },
        { "property": "paramDMod", "value": 0.0 },
        { "property": "paramDModType", "value": "none" },
        { "property": "paramDIter", "value": 0.0 },
        { "property": "paramDIterFunc", "value": "none" },
        { "property": "paramE", "value": 0.0 },
        { "property": "paramEMod", "value": 0.0 },
        { "property": "paramEModType", "value": "none" },
        { "property": "paramEIter", "value": 0.0 },
        { "property": "paramEIterFunc", "value": "none" },
        { "property": "modDelay", "value": 0 },
        { "property": "i", "value": 31 }
      ]
    },
    {
      "name": "Flatbox_city_flair_accentcstroke_accentbfill_ft6Iq-zQ_A",
      "shape": "Flatbox",
      "properties": [
        { "property": "x", "value": -11480 },
        { "property": "xMod", "value": 0.0 },
        { "property": "xModType", "value": "none" },
        { "property": "xIter", "value": 12600.0 },
        { "property": "xIterFunc", "value": "sin(x)" },
        { "property": "xr", "value": 90 },
        { "property": "xrMod", "value": 0.0 },
        { "property": "xrModType", "value": "none" },
        { "property": "xrIter", "value": 0.0 },
        { "property": "xrIterFunc", "value": "none" },
        { "property": "y", "value": -4850 },
        { "property": "yMod", "value": 0.0 },
        { "property": "yModType", "value": "none" },
        { "property": "yIter", "value": 400.0 },
        { "property": "yIterFunc", "value": "random 100" },
        { "property": "yr", "value": 0 },
        { "property": "yrMod", "value": 0.0 },
        { "property": "yrModType", "value": "none" },
        { "property": "yrIter", "value": 0.0 },
        { "property": "yrIterFunc", "value": "none" },
        { "property": "z", "value": -46000 },
        { "property": "zMod", "value": 0.0 },
        { "property": "zModType", "value": "none" },
        { "property": "zIter", "value": 548.0 },
        { "property": "zIterFunc", "value": "none" },
        { "property": "zr", "value": 45 },
        { "property": "zrMod", "value": 0.0 },
        { "property": "zrModType", "value": "none" },
        { "property": "zrIter", "value": 10.0 },
        { "property": "zrIterFunc", "value": "none" },
        { "property": "w", "value": 465.0 },
        { "property": "wMod", "value": 0.0 },
        { "property": "wModType", "value": "none" },
        { "property": "wIter", "value": 0.0 },
        { "property": "wIterFunc", "value": "none" },
        { "property": "h", "value": 600.0 },
        { "property": "hMod", "value": 0.0 },
        { "property": "hModType", "value": "none" },
        { "property": "hIter", "value": 0.0 },
        { "property": "hIterFunc", "value": "none" },
        { "property": "l", "value": 7282.0 },
        { "property": "lMod", "value": 0.0 },
        { "property": "lModType", "value": "none" },
        { "property": "lIter", "value": -800.0 },
        { "property": "lIterFunc", "value": "random 100" },
        { "property": "s", "value": 100.0 },
        { "property": "sMod", "value": 0.0 },
        { "property": "sModType", "value": "none" },
        { "property": "sIter", "value": 0.0 },
        { "property": "sIterFunc", "value": "none" },
        { "property": "strokeColor", "value": -1005167 },
        { "property": "strokeColorMod", "value": 0.0 },
        { "property": "strokeColorModType", "value": "none" },
        { "property": "strokeColorIter", "value": 0.0 },
        { "property": "strokeColorIterFunc", "value": "none" },
        { "property": "strokeWeight", "value": 2.0 },
        { "property": "strokeWeightMod", "value": 0.0 },
        { "property": "strokeWeightModType", "value": "none" },
        { "property": "strokeWeightIter", "value": 0.0 },
        { "property": "strokeWeightIterFunc", "value": "none" },
        { "property": "fillColor", "value": -4597324 },
        { "property": "fillColorMod", "value": 0.0 },
        { "property": "fillColorModType", "value": "none" },
        { "property": "fillColorIter", "value": 0.0 },
        { "property": "fillColorIterFunc", "value": "none" },
        { "property": "paramA", "value": 0.0 },
        { "property": "paramAMod", "value": 0.0 },
        { "property": "paramAModType", "value": "none" },
        { "property": "paramAIter", "value": 0.0 },
        { "property": "paramAIterFunc", "value": "none" },
        { "property": "paramB", "value": 0.0 },
        { "property": "paramBMod", "value": 0.0 },
        { "property": "paramBModType", "value": "none" },
        { "property": "paramBIter", "value": 0.0 },
        { "property": "paramBIterFunc", "value": "none" },
        { "property": "paramC", "value": 0.0 },
        { "property": "paramCMod", "value": 0.0 },
        { "property": "paramCModType", "value": "none" },
        { "property": "paramCIter", "value": 0.0 },
        { "property": "paramCIterFunc", "value": "none" },
        { "property": "paramD", "value": 0.0 },
        { "property": "paramDMod", "value": 0.0 },
        { "property": "paramDModType", "value": "none" },
        { "property": "paramDIter", "value": 0.0 },
        { "property": "paramDIterFunc", "value": "none" },
        { "property": "paramE", "value": 0.0 },
        { "property": "paramEMod", "value": 0.0 },
        { "property": "paramEModType", "value": "none" },
        { "property": "paramEIter", "value": 0.0 },
        { "property": "paramEIterFunc", "value": "none" },
        { "property": "modDelay", "value": 0 },
        { "property": "i", "value": 46 }
      ]
    },
    {
      "name": "Flatbox_basepole_accentafill_accentbstroke_zw0Seer3-7",
      "shape": "Flatbox",
      "properties": [
        { "property": "x", "value": 403 },
        { "property": "xMod", "value": 0.0 },
        { "property": "xModType", "value": "none" },
        { "property": "xIter", "value": 20.0 },
        { "property": "xIterFunc", "value": "none" },
        { "property": "xr", "value": 90 },
        { "property": "xrMod", "value": 0.0 },
        { "property": "xrModType", "value": "none" },
        { "property": "xrIter", "value": 0.0 },
        { "property": "xrIterFunc", "value": "none" },
        { "property": "y", "value": 200 },
        { "property": "yMod", "value": 0.0 },
        { "property": "yModType", "value": "none" },
        { "property": "yIter", "value": 0.0 },
        { "property": "yIterFunc", "value": "none" },
        { "property": "yr", "value": 0 },
        { "property": "yrMod", "value": 0.0 },
        { "property": "yrModType", "value": "none" },
        { "property": "yrIter", "value": 0.0 },
        { "property": "yrIterFunc", "value": "none" },
        { "property": "z", "value": 345 },
        { "property": "zMod", "value": 0.0 },
        { "property": "zModType", "value": "none" },
        { "property": "zIter", "value": -566.0 },
        { "property": "zIterFunc", "value": "none" },
        { "property": "zr", "value": 0 },
        { "property": "zrMod", "value": 0.0 },
        { "property": "zrModType", "value": "none" },
        { "property": "zrIter", "value": 65.0 },
        { "property": "zrIterFunc", "value": "random 100" },
        { "property": "w", "value": -50.0 },
        { "property": "wMod", "value": 0.0 },
        { "property": "wModType", "value": "none" },
        { "property": "wIter", "value": 0.0 },
        { "property": "wIterFunc", "value": "none" },
        { "property": "h", "value": 60.0 },
        { "property": "hMod", "value": 0.0 },
        { "property": "hModType", "value": "none" },
        { "property": "hIter", "value": 0.0 },
        { "property": "hIterFunc", "value": "none" },
        { "property": "l", "value": 1110.0 },
        { "property": "lMod", "value": 0.0 },
        { "property": "lModType", "value": "none" },
        { "property": "lIter", "value": 0.0 },
        { "property": "lIterFunc", "value": "none" },
        { "property": "s", "value": 100.0 },
        { "property": "sMod", "value": 0.0 },
        { "property": "sModType", "value": "none" },
        { "property": "sIter", "value": 0.0 },
        { "property": "sIterFunc", "value": "none" },
        { "property": "strokeColor", "value": -4597324 },
        { "property": "strokeColorMod", "value": 0.0 },
        { "property": "strokeColorModType", "value": "none" },
        { "property": "strokeColorIter", "value": 0.0 },
        { "property": "strokeColorIterFunc", "value": "none" },
        { "property": "strokeWeight", "value": 2.0 },
        { "property": "strokeWeightMod", "value": 0.0 },
        { "property": "strokeWeightModType", "value": "none" },
        { "property": "strokeWeightIter", "value": 0.0 },
        { "property": "strokeWeightIterFunc", "value": "none" },
        { "property": "fillColor", "value": -5221004 },
        { "property": "fillColorMod", "value": 0.0 },
        { "property": "fillColorModType", "value": "none" },
        { "property": "fillColorIter", "value": 0.0 },
        { "property": "fillColorIterFunc", "value": "none" },
        { "property": "paramA", "value": 0.0 },
        { "property": "paramAMod", "value": 0.0 },
        { "property": "paramAModType", "value": "none" },
        { "property": "paramAIter", "value": 0.0 },
        { "property": "paramAIterFunc", "value": "none" },
        { "property": "paramB", "value": 0.0 },
        { "property": "paramBMod", "value": 0.0 },
        { "property": "paramBModType", "value": "none" },
        { "property": "paramBIter", "value": 0.0 },
        { "property": "paramBIterFunc", "value": "none" },
        { "property": "paramC", "value": 0.0 },
        { "property": "paramCMod", "value": 0.0 },
        { "property": "paramCModType", "value": "none" },
        { "property": "paramCIter", "value": 0.0 },
        { "property": "paramCIterFunc", "value": "none" },
        { "property": "paramD", "value": 0.0 },
        { "property": "paramDMod", "value": 0.0 },
        { "property": "paramDModType", "value": "none" },
        { "property": "paramDIter", "value": 0.0 },
        { "property": "paramDIterFunc", "value": "none" },
        { "property": "paramE", "value": 0.0 },
        { "property": "paramEMod", "value": 0.0 },
        { "property": "paramEModType", "value": "none" },
        { "property": "paramEIter", "value": 0.0 },
        { "property": "paramEIterFunc", "value": "none" },
        { "property": "modDelay", "value": 0 },
        { "property": "i", "value": 75 }
      ]
    },
    {
      "name": "Rectangle_floor_accentcfill_YeU-eQkImS",
      "shape": "Rectangle",
      "properties": [
        { "property": "x", "value": 0 },
        { "property": "xMod", "value": 0.0 },
        { "property": "xModType", "value": "none" },
        { "property": "xIter", "value": 0.0 },
        { "property": "xIterFunc", "value": "none" },
        { "property": "xr", "value": 90 },
        { "property": "xrMod", "value": 0.0 },
        { "property": "xrModType", "value": "none" },
        { "property": "xrIter", "value": 0.0 },
        { "property": "xrIterFunc", "value": "none" },
        { "property": "y", "value": 356 },
        { "property": "yMod", "value": 0.0 },
        { "property": "yModType", "value": "none" },
        { "property": "yIter", "value": 0.0 },
        { "property": "yIterFunc", "value": "none" },
        { "property": "yr", "value": 0 },
        { "property": "yrMod", "value": 0.0 },
        { "property": "yrModType", "value": "none" },
        { "property": "yrIter", "value": 0.0 },
        { "property": "yrIterFunc", "value": "none" },
        { "property": "z", "value": -20000 },
        { "property": "zMod", "value": 0.0 },
        { "property": "zModType", "value": "none" },
        { "property": "zIter", "value": 0.0 },
        { "property": "zIterFunc", "value": "none" },
        { "property": "zr", "value": 0 },
        { "property": "zrMod", "value": 0.0 },
        { "property": "zrModType", "value": "none" },
        { "property": "zrIter", "value": 0.0 },
        { "property": "zrIterFunc", "value": "none" },
        { "property": "w", "value": 100000.0 },
        { "property": "wMod", "value": 0.0 },
        { "property": "wModType", "value": "none" },
        { "property": "wIter", "value": 0.0 },
        { "property": "wIterFunc", "value": "none" },
        { "property": "h", "value": 60000.0 },
        { "property": "hMod", "value": 0.0 },
        { "property": "hModType", "value": "none" },
        { "property": "hIter", "value": 0.0 },
        { "property": "hIterFunc", "value": "none" },
        { "property": "l", "value": 0.0 },
        { "property": "lMod", "value": 0.0 },
        { "property": "lModType", "value": "none" },
        { "property": "lIter", "value": 0.0 },
        { "property": "lIterFunc", "value": "none" },
        { "property": "s", "value": 0.0 },
        { "property": "sMod", "value": 0.0 },
        { "property": "sModType", "value": "none" },
        { "property": "sIter", "value": 0.0 },
        { "property": "sIterFunc", "value": "none" },
        { "property": "strokeColor", "value": -1005167 },
        { "property": "strokeColorMod", "value": 0.0 },
        { "property": "strokeColorModType", "value": "none" },
        { "property": "strokeColorIter", "value": 0.0 },
        { "property": "strokeColorIterFunc", "value": "none" },
        { "property": "strokeWeight", "value": 2.0 },
        { "property": "strokeWeightMod", "value": 0.0 },
        { "property": "strokeWeightModType", "value": "none" },
        { "property": "strokeWeightIter", "value": 0.0 },
        { "property": "strokeWeightIterFunc", "value": "none" },
        { "property": "fillColor", "value": -1005167 },
        { "property": "fillColorMod", "value": 0.0 },
        { "property": "fillColorModType", "value": "none" },
        { "property": "fillColorIter", "value": 0.0 },
        { "property": "fillColorIterFunc", "value": "none" },
        { "property": "paramA", "value": 0.0 },
        { "property": "paramAMod", "value": 0.0 },
        { "property": "paramAModType", "value": "none" },
        { "property": "paramAIter", "value": 0.0 },
        { "property": "paramAIterFunc", "value": "none" },
        { "property": "paramB", "value": 0.0 },
        { "property": "paramBMod", "value": 0.0 },
        { "property": "paramBModType", "value": "none" },
        { "property": "paramBIter", "value": 0.0 },
        { "property": "paramBIterFunc", "value": "none" },
        { "property": "paramC", "value": 0.0 },
        { "property": "paramCMod", "value": 0.0 },
        { "property": "paramCModType", "value": "none" },
        { "property": "paramCIter", "value": 0.0 },
        { "property": "paramCIterFunc", "value": "none" },
        { "property": "paramD", "value": 0.0 },
        { "property": "paramDMod", "value": 0.0 },
        { "property": "paramDModType", "value": "none" },
        { "property": "paramDIter", "value": 0.0 },
        { "property": "paramDIterFunc", "value": "none" },
        { "property": "paramE", "value": 0.0 },
        { "property": "paramEMod", "value": 0.0 },
        { "property": "paramEModType", "value": "none" },
        { "property": "paramEIter", "value": 0.0 },
        { "property": "paramEIterFunc", "value": "none" },
        { "property": "modDelay", "value": 0 },
        { "property": "i", "value": 1 }
      ]
    },
    {
      "name": "Triangle_leftvalley_accentbfill_bsOelKQfRJ",
      "shape": "Triangle",
      "properties": [
        { "property": "x", "value": -93326 },
        { "property": "xMod", "value": 0.0 },
        { "property": "xModType", "value": "none" },
        { "property": "xIter", "value": 0.0 },
        { "property": "xIterFunc", "value": "none" },
        { "property": "xr", "value": 0 },
        { "property": "xrMod", "value": 0.0 },
        { "property": "xrModType", "value": "none" },
        { "property": "xrIter", "value": 0.0 },
        { "property": "xrIterFunc", "value": "none" },
        { "property": "y", "value": 0 },
        { "property": "yMod", "value": 0.0 },
        { "property": "yModType", "value": "none" },
        { "property": "yIter", "value": 0.0 },
        { "property": "yIterFunc", "value": "none" },
        { "property": "yr", "value": 0 },
        { "property": "yrMod", "value": 0.0 },
        { "property": "yrModType", "value": "none" },
        { "property": "yrIter", "value": 0.0 },
        { "property": "yrIterFunc", "value": "none" },
        { "property": "z", "value": -72000 },
        { "property": "zMod", "value": 0.0 },
        { "property": "zModType", "value": "none" },
        { "property": "zIter", "value": 0.0 },
        { "property": "zIterFunc", "value": "none" },
        { "property": "zr", "value": 0 },
        { "property": "zrMod", "value": 0.0 },
        { "property": "zrModType", "value": "none" },
        { "property": "zrIter", "value": 0.0 },
        { "property": "zrIterFunc", "value": "none" },
        { "property": "w", "value": 301435.0 },
        { "property": "wMod", "value": 0.0 },
        { "property": "wModType", "value": "none" },
        { "property": "wIter", "value": 0.0 },
        { "property": "wIterFunc", "value": "none" },
        { "property": "h", "value": 118326.0 },
        { "property": "hMod", "value": 0.0 },
        { "property": "hModType", "value": "none" },
        { "property": "hIter", "value": 0.0 },
        { "property": "hIterFunc", "value": "none" },
        { "property": "l", "value": 0.0 },
        { "property": "lMod", "value": 0.0 },
        { "property": "lModType", "value": "none" },
        { "property": "lIter", "value": 0.0 },
        { "property": "lIterFunc", "value": "none" },
        { "property": "s", "value": 100.0 },
        { "property": "sMod", "value": 0.0 },
        { "property": "sModType", "value": "none" },
        { "property": "sIter", "value": 0.0 },
        { "property": "sIterFunc", "value": "none" },
        { "property": "strokeColor", "value": -4597324 },
        { "property": "strokeColorMod", "value": 0.0 },
        { "property": "strokeColorModType", "value": "none" },
        { "property": "strokeColorIter", "value": 0.0 },
        { "property": "strokeColorIterFunc", "value": "none" },
        { "property": "strokeWeight", "value": 2.0 },
        { "property": "strokeWeightMod", "value": 0.0 },
        { "property": "strokeWeightModType", "value": "none" },
        { "property": "strokeWeightIter", "value": 0.0 },
        { "property": "strokeWeightIterFunc", "value": "none" },
        { "property": "fillColor", "value": -4597324 },
        { "property": "fillColorMod", "value": 0.0 },
        { "property": "fillColorModType", "value": "none" },
        { "property": "fillColorIter", "value": 0.0 },
        { "property": "fillColorIterFunc", "value": "none" },
        { "property": "paramA", "value": 0.0 },
        { "property": "paramAMod", "value": 0.0 },
        { "property": "paramAModType", "value": "none" },
        { "property": "paramAIter", "value": 0.0 },
        { "property": "paramAIterFunc", "value": "none" },
        { "property": "paramB", "value": 0.0 },
        { "property": "paramBMod", "value": 0.0 },
        { "property": "paramBModType", "value": "none" },
        { "property": "paramBIter", "value": 0.0 },
        { "property": "paramBIterFunc", "value": "none" },
        { "property": "paramC", "value": 0.0 },
        { "property": "paramCMod", "value": 0.0 },
        { "property": "paramCModType", "value": "none" },
        { "property": "paramCIter", "value": 0.0 },
        { "property": "paramCIterFunc", "value": "none" },
        { "property": "paramD", "value": 0.0 },
        { "property": "paramDMod", "value": 0.0 },
        { "property": "paramDModType", "value": "none" },
        { "property": "paramDIter", "value": 0.0 },
        { "property": "paramDIterFunc", "value": "none" },
        { "property": "paramE", "value": 0.0 },
        { "property": "paramEMod", "value": 0.0 },
        { "property": "paramEModType", "value": "none" },
        { "property": "paramEIter", "value": 0.0 },
        { "property": "paramEIterFunc", "value": "none" },
        { "property": "variation", "value": "left-right" },
        { "property": "modDelay", "value": 0 },
        { "property": "i", "value": 1 }
      ]
    },
    {
      "name": "background",
      "shape": "OavpObject",
      "properties": [
        { "property": "x", "value": 0 },
        { "property": "xMod", "value": 0.0 },
        { "property": "xModType", "value": "none" },
        { "property": "xIter", "value": 0.0 },
        { "property": "xIterFunc", "value": "none" },
        { "property": "xr", "value": 0 },
        { "property": "xrMod", "value": 0.0 },
        { "property": "xrModType", "value": "none" },
        { "property": "xrIter", "value": 0.0 },
        { "property": "xrIterFunc", "value": "none" },
        { "property": "y", "value": 0 },
        { "property": "yMod", "value": 0.0 },
        { "property": "yModType", "value": "none" },
        { "property": "yIter", "value": 0.0 },
        { "property": "yIterFunc", "value": "none" },
        { "property": "yr", "value": 0 },
        { "property": "yrMod", "value": 0.0 },
        { "property": "yrModType", "value": "none" },
        { "property": "yrIter", "value": 0.0 },
        { "property": "yrIterFunc", "value": "none" },
        { "property": "z", "value": 0 },
        { "property": "zMod", "value": 0.0 },
        { "property": "zModType", "value": "none" },
        { "property": "zIter", "value": 0.0 },
        { "property": "zIterFunc", "value": "none" },
        { "property": "zr", "value": 0 },
        { "property": "zrMod", "value": 0.0 },
        { "property": "zrModType", "value": "none" },
        { "property": "zrIter", "value": 0.0 },
        { "property": "zrIterFunc", "value": "none" },
        { "property": "w", "value": 100.0 },
        { "property": "wMod", "value": 0.0 },
        { "property": "wModType", "value": "none" },
        { "property": "wIter", "value": 0.0 },
        { "property": "wIterFunc", "value": "none" },
        { "property": "h", "value": 100.0 },
        { "property": "hMod", "value": 0.0 },
        { "property": "hModType", "value": "none" },
        { "property": "hIter", "value": 0.0 },
        { "property": "hIterFunc", "value": "none" },
        { "property": "l", "value": 0.0 },
        { "property": "lMod", "value": 0.0 },
        { "property": "lModType", "value": "none" },
        { "property": "lIter", "value": 0.0 },
        { "property": "lIterFunc", "value": "none" },
        { "property": "s", "value": 100.0 },
        { "property": "sMod", "value": 0.0 },
        { "property": "sModType", "value": "none" },
        { "property": "sIter", "value": 0.0 },
        { "property": "sIterFunc", "value": "none" },
        { "property": "strokeColor", "value": -4597324 },
        { "property": "strokeColorMod", "value": 0.0 },
        { "property": "strokeColorModType", "value": "none" },
        { "property": "strokeColorIter", "value": 0.0 },
        { "property": "strokeColorIterFunc", "value": "none" },
        { "property": "strokeWeight", "value": 2.0 },
        { "property": "strokeWeightMod", "value": 0.0 },
        { "property": "strokeWeightModType", "value": "none" },
        { "property": "strokeWeightIter", "value": 0.0 },
        { "property": "strokeWeightIterFunc", "value": "none" },
        { "property": "fillColor", "value": -3043697 },
        { "property": "fillColorMod", "value": 0.0 },
        { "property": "fillColorModType", "value": "none" },
        { "property": "fillColorIter", "value": 0.0 },
        { "property": "fillColorIterFunc", "value": "none" },
        { "property": "paramA", "value": 0.0 },
        { "property": "paramAMod", "value": 0.0 },
        { "property": "paramAModType", "value": "none" },
        { "property": "paramAIter", "value": 0.0 },
        { "property": "paramAIterFunc", "value": "none" },
        { "property": "paramB", "value": 0.0 },
        { "property": "paramBMod", "value": 0.0 },
        { "property": "paramBModType", "value": "none" },
        { "property": "paramBIter", "value": 0.0 },
        { "property": "paramBIterFunc", "value": "none" },
        { "property": "paramC", "value": 0.0 },
        { "property": "paramCMod", "value": 0.0 },
        { "property": "paramCModType", "value": "none" },
        { "property": "paramCIter", "value": 0.0 },
        { "property": "paramCIterFunc", "value": "none" },
        { "property": "paramD", "value": 0.0 },
        { "property": "paramDMod", "value": 0.0 },
        { "property": "paramDModType", "value": "none" },
        { "property": "paramDIter", "value": 0.0 },
        { "property": "paramDIterFunc", "value": "none" },
        { "property": "paramE", "value": 0.0 },
        { "property": "paramEMod", "value": 0.0 },
        { "property": "paramEModType", "value": "none" },
        { "property": "paramEIter", "value": 0.0 },
        { "property": "paramEIterFunc", "value": "none" },
        { "property": "modDelay", "value": 0 },
        { "property": "i", "value": 1 }
      ]
    },
    {
      "name": "Rectangle_horizon_nostroke_accentafill_WP4VPGf2V",
      "shape": "Rectangle",
      "properties": [
        { "property": "x", "value": 0 },
        { "property": "xMod", "value": 0.0 },
        { "property": "xModType", "value": "none" },
        { "property": "xIter", "value": 0.0 },
        { "property": "xIterFunc", "value": "none" },
        { "property": "xr", "value": 0 },
        { "property": "xrMod", "value": 0.0 },
        { "property": "xrModType", "value": "none" },
        { "property": "xrIter", "value": 0.0 },
        { "property": "xrIterFunc", "value": "none" },
        { "property": "y", "value": 40000 },
        { "property": "yMod", "value": 0.0 },
        { "property": "yModType", "value": "none" },
        { "property": "yIter", "value": 0.0 },
        { "property": "yIterFunc", "value": "none" },
        { "property": "yr", "value": 0 },
        { "property": "yrMod", "value": 0.0 },
        { "property": "yrModType", "value": "none" },
        { "property": "yrIter", "value": 0.0 },
        { "property": "yrIterFunc", "value": "none" },
        { "property": "z", "value": -65000 },
        { "property": "zMod", "value": 0.0 },
        { "property": "zModType", "value": "none" },
        { "property": "zIter", "value": 0.0 },
        { "property": "zIterFunc", "value": "none" },
        { "property": "zr", "value": 0 },
        { "property": "zrMod", "value": 0.0 },
        { "property": "zrModType", "value": "none" },
        { "property": "zrIter", "value": 0.0 },
        { "property": "zrIterFunc", "value": "none" },
        { "property": "w", "value": 200000.0 },
        { "property": "wMod", "value": 0.0 },
        { "property": "wModType", "value": "none" },
        { "property": "wIter", "value": 0.0 },
        { "property": "wIterFunc", "value": "none" },
        { "property": "h", "value": 80000.0 },
        { "property": "hMod", "value": 0.0 },
        { "property": "hModType", "value": "none" },
        { "property": "hIter", "value": 0.0 },
        { "property": "hIterFunc", "value": "none" },
        { "property": "l", "value": 0.0 },
        { "property": "lMod", "value": 0.0 },
        { "property": "lModType", "value": "none" },
        { "property": "lIter", "value": 0.0 },
        { "property": "lIterFunc", "value": "none" },
        { "property": "s", "value": 0.0 },
        { "property": "sMod", "value": 0.0 },
        { "property": "sModType", "value": "none" },
        { "property": "sIter", "value": 0.0 },
        { "property": "sIterFunc", "value": "none" },
        { "property": "strokeColor", "value": 0 },
        { "property": "strokeColorMod", "value": 0.0 },
        { "property": "strokeColorModType", "value": "none" },
        { "property": "strokeColorIter", "value": 0.0 },
        { "property": "strokeColorIterFunc", "value": "none" },
        { "property": "strokeWeight", "value": 2.0 },
        { "property": "strokeWeightMod", "value": 0.0 },
        { "property": "strokeWeightModType", "value": "none" },
        { "property": "strokeWeightIter", "value": 0.0 },
        { "property": "strokeWeightIterFunc", "value": "none" },
        { "property": "fillColor", "value": -5221004 },
        { "property": "fillColorMod", "value": 0.0 },
        { "property": "fillColorModType", "value": "none" },
        { "property": "fillColorIter", "value": 0.0 },
        { "property": "fillColorIterFunc", "value": "none" },
        { "property": "paramA", "value": 0.0 },
        { "property": "paramAMod", "value": 0.0 },
        { "property": "paramAModType", "value": "none" },
        { "property": "paramAIter", "value": 0.0 },
        { "property": "paramAIterFunc", "value": "none" },
        { "property": "paramB", "value": 0.0 },
        { "property": "paramBMod", "value": 0.0 },
        { "property": "paramBModType", "value": "none" },
        { "property": "paramBIter", "value": 0.0 },
        { "property": "paramBIterFunc", "value": "none" },
        { "property": "paramC", "value": 0.0 },
        { "property": "paramCMod", "value": 0.0 },
        { "property": "paramCModType", "value": "none" },
        { "property": "paramCIter", "value": 0.0 },
        { "property": "paramCIterFunc", "value": "none" },
        { "property": "paramD", "value": 0.0 },
        { "property": "paramDMod", "value": 0.0 },
        { "property": "paramDModType", "value": "none" },
        { "property": "paramDIter", "value": 0.0 },
        { "property": "paramDIterFunc", "value": "none" },
        { "property": "paramE", "value": 0.0 },
        { "property": "paramEMod", "value": 0.0 },
        { "property": "paramEModType", "value": "none" },
        { "property": "paramEIter", "value": 0.0 },
        { "property": "paramEIterFunc", "value": "none" },
        { "property": "modDelay", "value": 0 },
        { "property": "i", "value": 1 }
      ]
    },
    {
      "name": "Triangle_rightvalley_accentcfill_E4gdX6tK4Z",
      "shape": "Triangle",
      "properties": [
        { "property": "x", "value": -50231 },
        { "property": "xMod", "value": 0.0 },
        { "property": "xModType", "value": "none" },
        { "property": "xIter", "value": 0.0 },
        { "property": "xIterFunc", "value": "none" },
        { "property": "xr", "value": 0 },
        { "property": "xrMod", "value": 0.0 },
        { "property": "xrModType", "value": "none" },
        { "property": "xrIter", "value": 0.0 },
        { "property": "xrIterFunc", "value": "none" },
        { "property": "y", "value": 0 },
        { "property": "yMod", "value": 0.0 },
        { "property": "yModType", "value": "none" },
        { "property": "yIter", "value": 0.0 },
        { "property": "yIterFunc", "value": "none" },
        { "property": "yr", "value": 0 },
        { "property": "yrMod", "value": 0.0 },
        { "property": "yrModType", "value": "none" },
        { "property": "yrIter", "value": 0.0 },
        { "property": "yrIterFunc", "value": "none" },
        { "property": "z", "value": -70000 },
        { "property": "zMod", "value": 0.0 },
        { "property": "zModType", "value": "none" },
        { "property": "zIter", "value": 0.0 },
        { "property": "zIterFunc", "value": "none" },
        { "property": "zr", "value": 0 },
        { "property": "zrMod", "value": 0.0 },
        { "property": "zrModType", "value": "none" },
        { "property": "zrIter", "value": 0.0 },
        { "property": "zrIterFunc", "value": "none" },
        { "property": "w", "value": -311452.0 },
        { "property": "wMod", "value": 0.0 },
        { "property": "wModType", "value": "none" },
        { "property": "wIter", "value": 0.0 },
        { "property": "wIterFunc", "value": "none" },
        { "property": "h", "value": 75231.0 },
        { "property": "hMod", "value": 0.0 },
        { "property": "hModType", "value": "none" },
        { "property": "hIter", "value": 0.0 },
        { "property": "hIterFunc", "value": "none" },
        { "property": "l", "value": 0.0 },
        { "property": "lMod", "value": 0.0 },
        { "property": "lModType", "value": "none" },
        { "property": "lIter", "value": 0.0 },
        { "property": "lIterFunc", "value": "none" },
        { "property": "s", "value": 100.0 },
        { "property": "sMod", "value": 0.0 },
        { "property": "sModType", "value": "none" },
        { "property": "sIter", "value": 0.0 },
        { "property": "sIterFunc", "value": "none" },
        { "property": "strokeColor", "value": -3043697 },
        { "property": "strokeColorMod", "value": 0.0 },
        { "property": "strokeColorModType", "value": "none" },
        { "property": "strokeColorIter", "value": 0.0 },
        { "property": "strokeColorIterFunc", "value": "none" },
        { "property": "strokeWeight", "value": 2.0 },
        { "property": "strokeWeightMod", "value": 0.0 },
        { "property": "strokeWeightModType", "value": "none" },
        { "property": "strokeWeightIter", "value": 0.0 },
        { "property": "strokeWeightIterFunc", "value": "none" },
        { "property": "fillColor", "value": -1005167 },
        { "property": "fillColorMod", "value": 0.0 },
        { "property": "fillColorModType", "value": "none" },
        { "property": "fillColorIter", "value": 0.0 },
        { "property": "fillColorIterFunc", "value": "none" },
        { "property": "paramA", "value": 0.0 },
        { "property": "paramAMod", "value": 0.0 },
        { "property": "paramAModType", "value": "none" },
        { "property": "paramAIter", "value": 0.0 },
        { "property": "paramAIterFunc", "value": "none" },
        { "property": "paramB", "value": 0.0 },
        { "property": "paramBMod", "value": 0.0 },
        { "property": "paramBModType", "value": "none" },
        { "property": "paramBIter", "value": 0.0 },
        { "property": "paramBIterFunc", "value": "none" },
        { "property": "paramC", "value": 0.0 },
        { "property": "paramCMod", "value": 0.0 },
        { "property": "paramCModType", "value": "none" },
        { "property": "paramCIter", "value": 0.0 },
        { "property": "paramCIterFunc", "value": "none" },
        { "property": "paramD", "value": 0.0 },
        { "property": "paramDMod", "value": 0.0 },
        { "property": "paramDModType", "value": "none" },
        { "property": "paramDIter", "value": 0.0 },
        { "property": "paramDIterFunc", "value": "none" },
        { "property": "paramE", "value": 0.0 },
        { "property": "paramEMod", "value": 0.0 },
        { "property": "paramEModType", "value": "none" },
        { "property": "paramEIter", "value": 0.0 },
        { "property": "paramEIterFunc", "value": "none" },
        { "property": "variation", "value": "left-right" },
        { "property": "modDelay", "value": 0 },
        { "property": "i", "value": 1 }
      ]
    },
    {
      "name": "Box_fleet_main_accentafill_backgroundstroke_TLbYfE-aZj",
      "shape": "Box",
      "properties": [
        { "property": "x", "value": -17404 },
        { "property": "xMod", "value": 0.0 },
        { "property": "xModType", "value": "none" },
        { "property": "xIter", "value": -6366.0 },
        { "property": "xIterFunc", "value": "none" },
        { "property": "xr", "value": -4 },
        { "property": "xrMod", "value": 0.0 },
        { "property": "xrModType", "value": "none" },
        { "property": "xrIter", "value": 0.0 },
        { "property": "xrIterFunc", "value": "none" },
        { "property": "y", "value": -29879 },
        { "property": "yMod", "value": 0.0 },
        { "property": "yModType", "value": "none" },
        { "property": "yIter", "value": 1785.0 },
        { "property": "yIterFunc", "value": "none" },
        { "property": "yr", "value": 14 },
        { "property": "yrMod", "value": 0.0 },
        { "property": "yrModType", "value": "none" },
        { "property": "yrIter", "value": 0.0 },
        { "property": "yrIterFunc", "value": "none" },
        { "property": "z", "value": -90000 },
        { "property": "zMod", "value": 0.0 },
        { "property": "zModType", "value": "none" },
        { "property": "zIter", "value": -3618.0 },
        { "property": "zIterFunc", "value": "none" },
        { "property": "zr", "value": 0 },
        { "property": "zrMod", "value": 0.0 },
        { "property": "zrModType", "value": "none" },
        { "property": "zrIter", "value": 0.0 },
        { "property": "zrIterFunc", "value": "none" },
        { "property": "w", "value": 17523.0 },
        { "property": "wMod", "value": 0.0 },
        { "property": "wModType", "value": "none" },
        { "property": "wIter", "value": -4010.0 },
        { "property": "wIterFunc", "value": "none" },
        { "property": "h", "value": 1785.0 },
        { "property": "hMod", "value": 0.0 },
        { "property": "hModType", "value": "none" },
        { "property": "hIter", "value": -10.0 },
        { "property": "hIterFunc", "value": "none" },
        { "property": "l", "value": 5100.0 },
        { "property": "lMod", "value": 0.0 },
        { "property": "lModType", "value": "none" },
        { "property": "lIter", "value": -10.0 },
        { "property": "lIterFunc", "value": "none" },
        { "property": "s", "value": 100.0 },
        { "property": "sMod", "value": 0.0 },
        { "property": "sModType", "value": "none" },
        { "property": "sIter", "value": 0.0 },
        { "property": "sIterFunc", "value": "none" },
        { "property": "strokeColor", "value": -3043697 },
        { "property": "strokeColorMod", "value": 0.0 },
        { "property": "strokeColorModType", "value": "none" },
        { "property": "strokeColorIter", "value": 0.0 },
        { "property": "strokeColorIterFunc", "value": "none" },
        { "property": "strokeWeight", "value": 2.0 },
        { "property": "strokeWeightMod", "value": 0.0 },
        { "property": "strokeWeightModType", "value": "none" },
        { "property": "strokeWeightIter", "value": 0.0 },
        { "property": "strokeWeightIterFunc", "value": "none" },
        { "property": "fillColor", "value": -5221004 },
        { "property": "fillColorMod", "value": 0.0 },
        { "property": "fillColorModType", "value": "none" },
        { "property": "fillColorIter", "value": 0.0 },
        { "property": "fillColorIterFunc", "value": "none" },
        { "property": "paramA", "value": 0.0 },
        { "property": "paramAMod", "value": 0.0 },
        { "property": "paramAModType", "value": "none" },
        { "property": "paramAIter", "value": 0.0 },
        { "property": "paramAIterFunc", "value": "none" },
        { "property": "paramB", "value": 0.0 },
        { "property": "paramBMod", "value": 0.0 },
        { "property": "paramBModType", "value": "none" },
        { "property": "paramBIter", "value": 0.0 },
        { "property": "paramBIterFunc", "value": "none" },
        { "property": "paramC", "value": 0.0 },
        { "property": "paramCMod", "value": 0.0 },
        { "property": "paramCModType", "value": "none" },
        { "property": "paramCIter", "value": 0.0 },
        { "property": "paramCIterFunc", "value": "none" },
        { "property": "paramD", "value": 0.0 },
        { "property": "paramDMod", "value": 0.0 },
        { "property": "paramDModType", "value": "none" },
        { "property": "paramDIter", "value": 0.0 },
        { "property": "paramDIterFunc", "value": "none" },
        { "property": "paramE", "value": 0.0 },
        { "property": "paramEMod", "value": 0.0 },
        { "property": "paramEModType", "value": "none" },
        { "property": "paramEIter", "value": 0.0 },
        { "property": "paramEIterFunc", "value": "none" },
        { "property": "modDelay", "value": 0 },
        { "property": "i", "value": 3 }
      ]
    },
    {
      "name": "camera",
      "shape": "OavpObject",
      "properties": [
        { "property": "x", "value": 0 },
        { "property": "xMod", "value": 0.0 },
        { "property": "xModType", "value": "none" },
        { "property": "xIter", "value": 0.0 },
        { "property": "xIterFunc", "value": "none" },
        { "property": "xr", "value": 0 },
        { "property": "xrMod", "value": 0.0 },
        { "property": "xrModType", "value": "none" },
        { "property": "xrIter", "value": 0.0 },
        { "property": "xrIterFunc", "value": "none" },
        { "property": "y", "value": 0 },
        { "property": "yMod", "value": 0.0 },
        { "property": "yModType", "value": "none" },
        { "property": "yIter", "value": 0.0 },
        { "property": "yIterFunc", "value": "none" },
        { "property": "yr", "value": 0 },
        { "property": "yrMod", "value": 0.0 },
        { "property": "yrModType", "value": "none" },
        { "property": "yrIter", "value": 0.0 },
        { "property": "yrIterFunc", "value": "none" },
        { "property": "z", "value": 0 },
        { "property": "zMod", "value": 0.0 },
        { "property": "zModType", "value": "none" },
        { "property": "zIter", "value": 0.0 },
        { "property": "zIterFunc", "value": "none" },
        { "property": "zr", "value": 0 },
        { "property": "zrMod", "value": 0.0 },
        { "property": "zrModType", "value": "none" },
        { "property": "zrIter", "value": 0.0 },
        { "property": "zrIterFunc", "value": "none" },
        { "property": "w", "value": 0.0 },
        { "property": "wMod", "value": 0.0 },
        { "property": "wModType", "value": "none" },
        { "property": "wIter", "value": 0.0 },
        { "property": "wIterFunc", "value": "none" },
        { "property": "h", "value": 0.0 },
        { "property": "hMod", "value": 0.0 },
        { "property": "hModType", "value": "none" },
        { "property": "hIter", "value": 0.0 },
        { "property": "hIterFunc", "value": "none" },
        { "property": "l", "value": 0.0 },
        { "property": "lMod", "value": 0.0 },
        { "property": "lModType", "value": "none" },
        { "property": "lIter", "value": 0.0 },
        { "property": "lIterFunc", "value": "none" },
        { "property": "s", "value": 100.0 },
        { "property": "sMod", "value": 0.0 },
        { "property": "sModType", "value": "none" },
        { "property": "sIter", "value": 0.0 },
        { "property": "sIterFunc", "value": "none" },
        { "property": "strokeColor", "value": -3043697 },
        { "property": "strokeColorMod", "value": 0.0 },
        { "property": "strokeColorModType", "value": "none" },
        { "property": "strokeColorIter", "value": 0.0 },
        { "property": "strokeColorIterFunc", "value": "none" },
        { "property": "strokeWeight", "value": 2.0 },
        { "property": "strokeWeightMod", "value": 0.0 },
        { "property": "strokeWeightModType", "value": "none" },
        { "property": "strokeWeightIter", "value": 0.0 },
        { "property": "strokeWeightIterFunc", "value": "none" },
        { "property": "fillColor", "value": -5221004 },
        { "property": "fillColorMod", "value": 0.0 },
        { "property": "fillColorModType", "value": "none" },
        { "property": "fillColorIter", "value": 0.0 },
        { "property": "fillColorIterFunc", "value": "none" },
        { "property": "paramA", "value": 100000.0 },
        { "property": "paramAMod", "value": 0.0 },
        { "property": "paramAModType", "value": "none" },
        { "property": "paramAIter", "value": 0.0 },
        { "property": "paramAIterFunc", "value": "none" },
        { "property": "paramB", "value": 0.0 },
        { "property": "paramBMod", "value": 0.0 },
        { "property": "paramBModType", "value": "none" },
        { "property": "paramBIter", "value": 0.0 },
        { "property": "paramBIterFunc", "value": "none" },
        { "property": "paramC", "value": 0.0 },
        { "property": "paramCMod", "value": 0.0 },
        { "property": "paramCModType", "value": "none" },
        { "property": "paramCIter", "value": 0.0 },
        { "property": "paramCIterFunc", "value": "none" },
        { "property": "paramD", "value": 0.0 },
        { "property": "paramDMod", "value": 0.0 },
        { "property": "paramDModType", "value": "none" },
        { "property": "paramDIter", "value": 0.0 },
        { "property": "paramDIterFunc", "value": "none" },
        { "property": "paramE", "value": 0.0 },
        { "property": "paramEMod", "value": 0.0 },
        { "property": "paramEModType", "value": "none" },
        { "property": "paramEIter", "value": 0.0 },
        { "property": "paramEIterFunc", "value": "none" },
        { "property": "modDelay", "value": 0 },
        { "property": "i", "value": 1 }
      ]
    },
    {
      "name": "Flatbox_poletip_accentbfill_accentastroke_AnKoh3giJn",
      "shape": "Flatbox",
      "properties": [
        { "property": "x", "value": 403 },
        { "property": "xMod", "value": 0.0 },
        { "property": "xModType", "value": "none" },
        { "property": "xIter", "value": 20.0 },
        { "property": "xIterFunc", "value": "none" },
        { "property": "xr", "value": 90 },
        { "property": "xrMod", "value": 0.0 },
        { "property": "xrModType", "value": "none" },
        { "property": "xrIter", "value": 0.0 },
        { "property": "xrIterFunc", "value": "none" },
        { "property": "y", "value": -415 },
        { "property": "yMod", "value": 0.0 },
        { "property": "yModType", "value": "none" },
        { "property": "yIter", "value": 0.0 },
        { "property": "yIterFunc", "value": "none" },
        { "property": "yr", "value": 0 },
        { "property": "yrMod", "value": 0.0 },
        { "property": "yrModType", "value": "none" },
        { "property": "yrIter", "value": 0.0 },
        { "property": "yrIterFunc", "value": "none" },
        { "property": "z", "value": 345 },
        { "property": "zMod", "value": 0.0 },
        { "property": "zModType", "value": "none" },
        { "property": "zIter", "value": -566.0 },
        { "property": "zIterFunc", "value": "none" },
        { "property": "zr", "value": 0 },
        { "property": "zrMod", "value": 0.0 },
        { "property": "zrModType", "value": "none" },
        { "property": "zrIter", "value": 65.0 },
        { "property": "zrIterFunc", "value": "random 100" },
        { "property": "w", "value": -50.0 },
        { "property": "wMod", "value": 0.0 },
        { "property": "wModType", "value": "none" },
        { "property": "wIter", "value": 0.0 },
        { "property": "wIterFunc", "value": "none" },
        { "property": "h", "value": 106.0 },
        { "property": "hMod", "value": 0.0 },
        { "property": "hModType", "value": "none" },
        { "property": "hIter", "value": 0.0 },
        { "property": "hIterFunc", "value": "none" },
        { "property": "l", "value": 110.0 },
        { "property": "lMod", "value": 0.0 },
        { "property": "lModType", "value": "none" },
        { "property": "lIter", "value": 0.0 },
        { "property": "lIterFunc", "value": "none" },
        { "property": "s", "value": 100.0 },
        { "property": "sMod", "value": 0.0 },
        { "property": "sModType", "value": "none" },
        { "property": "sIter", "value": 0.0 },
        { "property": "sIterFunc", "value": "none" },
        { "property": "strokeColor", "value": -5221004 },
        { "property": "strokeColorMod", "value": 0.0 },
        { "property": "strokeColorModType", "value": "none" },
        { "property": "strokeColorIter", "value": 0.0 },
        { "property": "strokeColorIterFunc", "value": "none" },
        { "property": "strokeWeight", "value": 2.0 },
        { "property": "strokeWeightMod", "value": 0.0 },
        { "property": "strokeWeightModType", "value": "none" },
        { "property": "strokeWeightIter", "value": 0.0 },
        { "property": "strokeWeightIterFunc", "value": "none" },
        { "property": "fillColor", "value": -4597324 },
        { "property": "fillColorMod", "value": 0.0 },
        { "property": "fillColorModType", "value": "none" },
        { "property": "fillColorIter", "value": 0.0 },
        { "property": "fillColorIterFunc", "value": "none" },
        { "property": "paramA", "value": 0.0 },
        { "property": "paramAMod", "value": 0.0 },
        { "property": "paramAModType", "value": "none" },
        { "property": "paramAIter", "value": 0.0 },
        { "property": "paramAIterFunc", "value": "none" },
        { "property": "paramB", "value": 0.0 },
        { "property": "paramBMod", "value": 0.0 },
        { "property": "paramBModType", "value": "none" },
        { "property": "paramBIter", "value": 0.0 },
        { "property": "paramBIterFunc", "value": "none" },
        { "property": "paramC", "value": 0.0 },
        { "property": "paramCMod", "value": 0.0 },
        { "property": "paramCModType", "value": "none" },
        { "property": "paramCIter", "value": 0.0 },
        { "property": "paramCIterFunc", "value": "none" },
        { "property": "paramD", "value": 0.0 },
        { "property": "paramDMod", "value": 0.0 },
        { "property": "paramDModType", "value": "none" },
        { "property": "paramDIter", "value": 0.0 },
        { "property": "paramDIterFunc", "value": "none" },
        { "property": "paramE", "value": 0.0 },
        { "property": "paramEMod", "value": 0.0 },
        { "property": "paramEModType", "value": "none" },
        { "property": "paramEIter", "value": 0.0 },
        { "property": "paramEIterFunc", "value": "none" },
        { "property": "modDelay", "value": 0 },
        { "property": "i", "value": 75 }
      ]
    }
  ]
}
